In [2]:
import sys

In [3]:
print(sys.prefix)

f:\binance-etl\binance_env

In [4]:
import pandas as pd
import requests as req

In [21]:
# URLS
price_url = 'https://api.binance.com/api/v3/ticker/price'
trades = 'https://api.binance.com/api/v3/trades?symbol=ETHBTC&limit=5'

In [31]:
def get_prices():
    res = req.get(price_url)
    res.raise_for_status()

    data = res.json()
    print(data)
    return data

In [32]:
prices = get_prices()

[{'symbol': 'ETHBTC', 'price': '0.03127000'}, {'symbol': 'LTCBTC', 'price': '0.00074600'}, {'symbol': 'BNBBTC', 'price': '0.00837200'}, {'symbol': 'NEOBTC', 'price': '0.00003952'}, {'symbol': 'QTUMETH', 'price': '0.00046550'}, {'symbol': 'EOSETH', 'price': '0.00030670'}, {'symbol': 'SNTETH', 'price': '0.00001700'}, {'symbol': 'BNTETH', 'price': '0.00020260'}, {'symbol': 'BCCBTC', 'price': '0.00000000'}, {'symbol': 'GASBTC', 'price': '0.00002350'}, {'symbol': 'BNBETH', 'price': '0.26770000'}, {'symbol': 'BTCUSDT', 'price': '73644.49000000'}, {'symbol': 'ETHUSDT', 'price': '2302.76000000'}, {'symbol': 'HSRBTC', 'price': '0.00000000'}, {'symbol': 'OAXETH', 'price': '0.00000000'}, {'symbol': 'DNTETH', 'price': '0.00000000'}, {'symbol': 'MCOETH', 'price': '0.00000000'}, {'symbol': 'ICNETH', 'price': '0.00000000'}, {'symbol': 'MCOBTC', 'price': '0.00000000'}, {'symbol': 'WTCBTC', 'price': '0.00000024'}, {'symbol': 'WTCETH', 'price': '0.00000000'}, {'symbol': 'LRCBTC', 'price': '0.00000052'}, {'symbol': 'LRCETH', 'price': '0.00001675'}, {'symbol': 'QTUMBTC', 'price': '0.00001628'}, {'symbol': 'YOYOBTC', 'price': '0.00000000'}, {'symbol': 'OMGBTC', 'price': '0.00003080'}, {'symbol': 'OMGETH', 'price': '0.00079100'}, {'symbol': 'ZRXBTC', 'price': '0.00000154'}, {'symbol': 'ZRXETH', 'price': '0.00009940'}, {'symbol': 'STRATBTC', 'price': '0.00000000'}, {'symbol': 'STRATETH', 'price': '0.00000000'}, {'symbol': 'SNGLSBTC', 'price': '0.00000000'}, {'symbol': 'SNGLSETH', 'price': '0.00000000'}, {'symbol': 'BQXBTC', 'price': '0.00000000'}, {'symbol': 'BQXETH', 'price': '0.00000000'}, {'symbol': 'KNCBTC', 'price': '0.00000185'}, {'symbol': 'KNCETH', 'price': '0.00039410'}, {'symbol': 'FUNBTC', 'price': '0.00000000'}, {'symbol': 'FUNETH', 'price': '0.00000146'}, {'symbol': 'SNMBTC', 'price': '0.00000057'}, {'symbol': 'SNMETH', 'price': '0.00000000'}, {'symbol': 'NEOETH', 'price': '0.00477500'}, {'symbol': 'IOTABTC', 'price': '0.00000076'}, {'symbol': 'IOTAETH', 'price': '0.00003346'}, {'symbol': 'LINKBTC', 'price': '0.00012510'}, {'symbol': 'LINKETH', 'price': '0.00400300'}, {'symbol': 'XVGBTC', 'price': '0.00000000'}, {'symbol': 'XVGETH', 'price': '0.00000247'}, {'symbol': 'SALTBTC', 'price': '0.00000000'}, {'symbol': 'SALTETH', 'price': '0.00000000'}, {'symbol': 'MDABTC', 'price': '0.00000000'}, {'symbol': 'MDAETH', 'price': '0.00000000'}, {'symbol': 'MTLBTC', 'price': '0.00000405'}, {'symbol': 'MTLETH', 'price': '0.00068340'}, {'symbol': 'SUBBTC', 'price': '0.00000000'}, {'symbol': 'SUBETH', 'price': '0.00000000'}, {'symbol': 'EOSBTC', 'price': '0.00000716'}, {'symbol': 'SNTBTC', 'price': '0.00000032'}, {'symbol': 'ETCETH', 'price': '0.00387000'}, {'symbol': 'ETCBTC', 'price': '0.00011520'}, {'symbol': 'MTHBTC', 'price': '0.00000000'}, {'symbol': 'MTHETH', 'price': '0.00000000'}, {'symbol': 'ENGBTC', 'price': '0.00000000'}, {'symbol': 'ENGETH', 'price': '0.00000000'}, {'symbol': 'DNTBTC', 'price': '0.00000186'}, {'symbol': 'ZECBTC', 'price': '0.00463620'}, {'symbol': 'ZECETH', 'price': '0.14828000'}, {'symbol': 'BNTBTC', 'price': '0.00000794'}, {'symbol': 'ASTBTC', 'price': '0.00000124'}, {'symbol': 'ASTETH', 'price': '0.00000000'}, {'symbol': 'DASHBTC', 'price': '0.00050420'}, {'symbol': 'DASHETH', 'price': '0.02084000'}, {'symbol': 'OAXBTC', 'price': '0.00000038'}, {'symbol': 'ICNBTC', 'price': '0.00000000'}, {'symbol': 'BTGBTC', 'price': '0.00091300'}, {'symbol': 'BTGETH', 'price': '0.00000000'}, {'symbol': 'EVXBTC', 'price': '0.00000000'}, {'symbol': 'EVXETH', 'price': '0.00000000'}, {'symbol': 'REQBTC', 'price': '0.00000112'}, {'symbol': 'REQETH', 'price': '0.00000000'}, {'symbol': 'VIBBTC', 'price': '0.00000051'}, {'symbol': 'VIBETH', 'price': '0.00003450'}, {'symbol': 'HSRETH', 'price': '0.00000000'}, {'symbol': 'TRXBTC', 'price': '0.00000443'}, {'symbol': 'TRXETH', 'price': '0.00014163'}, {'symbol': 'POWRBTC', 'price': '0.00000094'}, {'symbol': 'POWRETH', 'price': '0.00002760'}, {'symbol': 'ARKBTC', 'price': '0.00001679'}, {'symbol': 'ARKETH', 'price': '0.00000000'}, {'symbol': 'YOYOETH', 'price': '0.00000000'}, {'symbol': 'XRPBTC', 'price': '0.00001906'}, {'symbol': 'XRPETH', 'price': '0.00060920'}, {'symbol': 'MODBTC', 'price': '0.00000000'}, {'symbol': 'MODETH', 'price': '0.00000000'}, {'symbol': 'ENJBTC', 'price': '0.00000035'}, {'symbol': 'ENJETH', 'price': '0.00006172'}, {'symbol': 'STORJBTC', 'price': '0.00000143'}, {'symbol': 'STORJETH', 'price': '0.00000000'}, {'symbol': 'BNBUSDT', 'price': '616.74000000'}, {'symbol': 'VENBNB', 'price': '0.00000000'}, {'symbol': 'YOYOBNB', 'price': '0.00000000'}, {'symbol': 'POWRBNB', 'price': '0.00000000'}, {'symbol': 'VENBTC', 'price': '0.00000000'}, {'symbol': 'VENETH', 'price': '0.00000000'}, {'symbol': 'KMDBTC', 'price': '0.00000015'}, {'symbol': 'KMDETH', 'price': '0.00000000'}, {'symbol': 'NULSBNB', 'price': '0.00000000'}, {'symbol': 'RCNBTC', 'price': '0.00000000'}, {'symbol': 'RCNETH', 'price': '0.00000000'}, {'symbol': 'RCNBNB', 'price': '0.00000000'}, {'symbol': 'NULSBTC', 'price': '0.00000030'}, {'symbol': 'NULSETH', 'price': '0.00000000'}, {'symbol': 'RDNBTC', 'price': '0.00000000'}, {'symbol': 'RDNETH', 'price': '0.00000000'}, {'symbol': 'RDNBNB', 'price': '0.00000000'}, {'symbol': 'XMRBTC', 'price': '0.00228700'}, {'symbol': 'XMRETH', 'price': '0.04032000'}, {'symbol': 'DLTBNB', 'price': '0.00000000'}, {'symbol': 'WTCBNB', 'price': '0.00000000'}, {'symbol': 'DLTBTC', 'price': '0.00000000'}, {'symbol': 'DLTETH', 'price': '0.00000000'}, {'symbol': 'AMBBTC', 'price': '0.00000010'}, {'symbol': 'AMBETH', 'price': '0.00000000'}, {'symbol': 'AMBBNB', 'price': '0.00000000'}, {'symbol': 'BCCETH', 'price': '0.00000000'}, {'symbol': 'BCCUSDT', 'price': '0.00000000'}, {'symbol': 'BCCBNB', 'price': '0.00000000'}, {'symbol': 'BATBTC', 'price': '0.00000136'}, {'symbol': 'BATETH', 'price': '0.00010630'}, {'symbol': 'BATBNB', 'price': '0.00000000'}, {'symbol': 'BCPTBTC', 'price': '0.00000000'}, {'symbol': 'BCPTETH', 'price': '0.00000000'}, {'symbol': 'BCPTBNB', 'price': '0.00000000'}, {'symbol': 'ARNBTC', 'price': '0.00000000'}, {'symbol': 'ARNETH', 'price': '0.00000000'}, {'symbol': 'GVTBTC', 'price': '0.00000000'}, {'symbol': 'GVTETH', 'price': '0.00000000'}, {'symbol': 'CDTBTC', 'price': '0.00000000'}, {'symbol': 'CDTETH', 'price': '0.00000000'}, {'symbol': 'GXSBTC', 'price': '0.00000000'}, {'symbol': 'GXSETH', 'price': '0.00000000'}, {'symbol': 'NEOUSDT', 'price': '2.90000000'}, {'symbol': 'NEOBNB', 'price': '0.03836000'}, {'symbol': 'POEBTC', 'price': '0.00000000'}, {'symbol': 'POEETH', 'price': '0.00000000'}, {'symbol': 'QSPBTC', 'price': '0.00000000'}, {'symbol': 'QSPETH', 'price': '0.00000000'}, {'symbol': 'QSPBNB', 'price': '0.00000000'}, {'symbol': 'BTSBTC', 'price': '0.00000043'}, {'symbol': 'BTSETH', 'price': '0.00000000'}, {'symbol': 'BTSBNB', 'price': '0.00000000'}, {'symbol': 'XZCBTC', 'price': '0.00000000'}, {'symbol': 'XZCETH', 'price': '0.00000000'}, {'symbol': 'XZCBNB', 'price': '0.00000000'}, {'symbol': 'LSKBTC', 'price': '0.00000186'}, {'symbol': 'LSKETH', 'price': '0.00033730'}, {'symbol': 'LSKBNB', 'price': '0.00000000'}, {'symbol': 'TNTBTC', 'price': '0.00000000'}, {'symbol': 'TNTETH', 'price': '0.00000000'}, {'symbol': 'FUELBTC', 'price': '0.00000000'}, {'symbol': 'FUELETH', 'price': '0.00000000'}, {'symbol': 'MANABTC', 'price': '0.00000147'}, {'symbol': 'MANAETH', 'price': '0.00004950'}, {'symbol': 'BCDBTC', 'price': '0.00000000'}, {'symbol': 'BCDETH', 'price': '0.00000000'}, {'symbol': 'DGDBTC', 'price': '0.00000000'}, {'symbol': 'DGDETH', 'price': '0.00000000'}, {'symbol': 'IOTABNB', 'price': '0.00071700'}, {'symbol': 'ADXBTC', 'price': '0.00000105'}, {'symbol': 'ADXETH', 'price': '0.00003007'}, {'symbol': 'ADXBNB', 'price': '0.00000000'}, {'symbol': 'ADABTC', 'price': '0.00000337'}, {'symbol': 'ADAETH', 'price': '0.00010790'}, {'symbol': 'PPTBTC', 'price': '0.00000000'}, {'symbol': 'PPTETH', 'price': '0.00000000'}, {'symbol': 'CMTBTC', 'price': '0.00000000'}, {'symbol': 'CMTETH', 'price': '0.00000000'}, {'symbol': 'CMTBNB', 'price': '0.00000000'}, {'symbol': 'XLMBTC', 'price': '0.00000218'}, {'symbol': 'XLMETH', 'price': '0.00006992'}, {'symbol': 'XLMBNB', 'price': '0.00030360'}, {'symbol': 'CNDBTC', 'price': '0.00000000'}, {'symbol': 'CNDETH', 'price': '0.00000000'}, {'symbol': 'CNDBNB', 'price': '0.00000000'}, {'symbol': 'LENDBTC', 'price': '0.00000000'}, {'symbol': 'LENDETH', 'price': '0.00000000'}, {'symbol': 'WABIBTC', 'price': '0.00000030'}, {'symbol': 'WABIETH', 'price': '0.00000000'}, {'symbol': 'WABIBNB', 'price': '0.00000000'}, {'symbol': 'LTCETH', 'price': '0.02392000'}, {'symbol': 'LTCUSDT', 'price': '54.96000000'}, {'symbol': 'LTCBNB', 'price': '0.08920000'}, {'symbol': 'TNBBTC', 'price': '0.00000000'}, {'symbol': 'TNBETH', 'price': '0.00000000'}, {'symbol': 'WAVESBTC', 'price': '0.00001626'}, {'symbol': 'WAVESETH', 'price': '0.00029800'}, {'symbol': 'WAVESBNB', 'price': '0.00513000'}, {'symbol': 'GTOBTC', 'price': '0.00000077'}, {'symbol': 'GTOETH', 'price': '0.00000000'}, {'symbol': 'GTOBNB', 'price': '0.00000000'}, {'symbol': 'ICXBTC', 'price': '0.00000056'}, {'symbol': 'ICXETH', 'price': '0.00011790'}, {'symbol': 'ICXBNB', 'price': '0.00000000'}, {'symbol': 'OSTBTC', 'price': '0.00000000'}, {'symbol': 'OSTETH', 'price': '0.00000000'}, {'symbol': 'OSTBNB', 'price': '0.00000000'}, {'symbol': 'ELFBTC', 'price': '0.00000274'}, {'symbol': 'ELFETH', 'price': '0.00014330'}, {'symbol': 'AIONBTC', 'price': '0.00000139'}, {'symbol': 'AIONETH', 'price': '0.00000000'}, {'symbol': 'AIONBNB', 'price': '0.00000000'}, {'symbol': 'NEBLBTC', 'price': '0.00001200'}, {'symbol': 'NEBLBNB', 'price': '0.00000000'}, {'symbol': 'BRDBTC', 'price': '0.00000000'}, {'symbol': 'BRDETH', 'price': '0.00000000'}, {'symbol': 'BRDBNB', 'price': '0.00000000'}, {'symbol': 'MCOBNB', 'price': '0.00000000'}, {'symbol': 'EDOBTC', 'price': '0.00000000'}, {'symbol': 'EDOETH', 'price': '0.00000000'}, {'symbol': 'WINGSBTC', 'price': '0.00000000'}, {'symbol': 'WINGSETH', 'price': '0.00000000'}, {'symbol': 'NAVBTC', 'price': '0.00000000'}, {'symbol': 'NAVETH', 'price': '0.00000000'}, {'symbol': 'NAVBNB', 'price': '0.00000000'}, {'symbol': 'LUNBTC', 'price': '0.00000000'}, {'symbol': 'LUNETH', 'price': '0.00000000'}, {'symbol': 'TRIGBTC', 'price': '0.00000000'}, {'symbol': 'TRIGETH', 'price': '0.00000000'}, {'symbol': 'TRIGBNB', 'price': '0.00000000'}, {'symbol': 'APPCBTC', 'price': '0.00000000'}, {'symbol': 'APPCETH', 'price': '0.00000000'}, {'symbol': 'APPCBNB', 'price': '0.00000000'}, {'symbol': 'VIBEBTC', 'price': '0.00000000'}, {'symbol': 'VIBEETH', 'price': '0.00000000'}, {'symbol': 'RLCBTC', 'price': '0.00000553'}, {'symbol': 'RLCETH', 'price': '0.00018420'}, {'symbol': 'RLCBNB', 'price': '0.00000000'}, {'symbol': 'INSBTC', 'price': '0.00000000'}, {'symbol': 'INSETH', 'price': '0.00000000'}, {'symbol': 'PIVXBTC', 'price': '0.00000147'}, {'symbol': 'PIVXBNB', 'price': '0.00000000'}, {'symbol': 'IOSTBTC', 'price': '0.00000010'}, {'symbol': 'IOSTETH', 'price': '0.00000372'}, {'symbol': 'CHATBTC', 'price': '0.00000000'}, {'symbol': 'CHATETH', 'price': '0.00000000'}, {'symbol': 'STEEMBTC', 'price': '0.00000079'}, {'symbol': 'STEEMETH', 'price': '0.00002531'}, {'symbol': 'STEEMBNB', 'price': '0.00000000'}, {'symbol': 'NANOBTC', 'price': '0.00000000'}, {'symbol': 'NANOETH', 'price': '0.00000000'}, {'symbol': 'NANOBNB', 'price': '0.00000000'}, {'symbol': 'VIABTC', 'price': '0.00000000'}, {'symbol': 'VIAETH', 'price': '0.00000000'}, {'symbol': 'VIABNB', 'price': '0.00000000'}, {'symbol': 'BLZBTC', 'price': '0.00000060'}, {'symbol': 'BLZETH', 'price': '0.00004159'}, {'symbol': 'BLZBNB', 'price': '0.00000000'}, {'symbol': 'AEBTC', 'price': '0.00000000'}, {'symbol': 'AEETH', 'price': '0.00000000'}, {'symbol': 'AEBNB', 'price': '0.00000000'}, {'symbol': 'RPXBTC', 'price': '0.00000000'}, {'symbol': 'RPXETH', 'price': '0.00000000'}, {'symbol': 'RPXBNB', 'price': '0.00000000'}, {'symbol': 'NCASHBTC', 'price': '0.00000000'}, {'symbol': 'NCASHETH', 'price': '0.00000000'}, {'symbol': 'NCASHBNB', 'price': '0.00000000'}, {'symbol': 'POABTC', 'price': '0.00000000'}, {'symbol': 'POAETH', 'price': '0.00000000'}, {'symbol': 'POABNB', 'price': '0.00000000'}, {'symbol': 'ZILBTC', 'price': '0.00000010'}, {'symbol': 'ZILETH', 'price': '0.00000168'}, {'symbol': 'ZILBNB', 'price': '0.00008858'}, {'symbol': 'ONTBTC', 'price': '0.00000101'}, {'symbol': 'ONTETH', 'price': '0.00012530'}, {'symbol': 'ONTBNB', 'price': '0.00000000'}, {'symbol': 'STORMBTC', 'price': '0.00000000'}, {'symbol': 'STORMETH', 'price': '0.00000000'}, {'symbol': 'STORMBNB', 'price': '0.00000000'}, {'symbol': 'QTUMBNB', 'price': '0.00000000'}, {'symbol': 'QTUMUSDT', 'price': '0.91800000'}, {'symbol': 'XEMBTC', 'price': '0.00000192'}, {'symbol': 'XEMETH', 'price': '0.00000000'}, {'symbol': 'XEMBNB', 'price': '0.00000000'}, {'symbol': 'WANBTC', 'price': '0.00000076'}, {'symbol': 'WANETH', 'price': '0.00009270'}, {'symbol': 'WANBNB', 'price': '0.00000000'}, {'symbol': 'WPRBTC', 'price': '0.00000000'}, {'symbol': 'WPRETH', 'price': '0.00000000'}, {'symbol': 'QLCBTC', 'price': '0.00000021'}, {'symbol': 'QLCETH', 'price': '0.00000000'}, {'symbol': 'SYSBTC', 'price': '0.00000019'}, {'symbol': 'SYSETH', 'price': '0.00000000'}, {'symbol': 'SYSBNB', 'price': '0.00000000'}, {'symbol': 'QLCBNB', 'price': '0.00000000'}, {'symbol': 'GRSBTC', 'price': '0.00000000'}, {'symbol': 'GRSETH', 'price': '0.00000000'}, {'symbol': 'ADAUSDT', 'price': '0.24820000'}, {'symbol': 'ADABNB', 'price': '0.00040300'}, {'symbol': 'CLOAKBTC', 'price': '0.00000000'}, {'symbol': 'CLOAKETH', 'price': '0.00000000'}, {'symbol': 'GNTBTC', 'price': '0.00000000'}, {'symbol': 'GNTETH', 'price': '0.00000000'}, {'symbol': 'GNTBNB', 'price': '0.00000000'}, {'symbol': 'LOOMBTC', 'price': '0.00000075'}, {'symbol': 'LOOMETH', 'price': '0.00003231'}, {'symbol': 'LOOMBNB', 'price': '0.00000000'}, {'symbol': 'XRPUSDT', 'price': '1.40350000'}, {'symbol': 'BCNBTC', 'price': '0.00000000'}, {'symbol': 'BCNETH', 'price': '0.00000000'}, {'symbol': 'BCNBNB', 'price': '0.00000000'}, {'symbol': 'REPBTC', 'price': '0.00034130'}, {'symbol': 'REPBNB', 'price': '0.00000000'}, {'symbol': 'BTCTUSD', 'price': '73469.60000000'}, {'symbol': 'TUSDBTC', 'price': '0.00000000'}, {'symbol': 'ETHTUSD', 'price': '2303.47000000'}, {'symbol': 'TUSDETH', 'price': '0.00000000'}, {'symbol': 'TUSDBNB', 'price': '0.00000000'}, {'symbol': 'ZENBTC', 'price': '0.00007848'}, {'symbol': 'ZENETH', 'price': '0.00399100'}, {'symbol': 'ZENBNB', 'price': '0.03290000'}, {'symbol': 'SKYCOINBTC', 'price': '0.00000000'}, {'symbol': 'SKYCOINETH', 'price': '0.00000000'}, {'symbol': 'SKYCOINBNB', 'price': '0.00000000'}, {'symbol': 'EOSUSDT', 'price': '0.77990000'}, {'symbol': 'EOSBNB', 'price': '0.00258300'}, {'symbol': 'CVCBTC', 'price': '0.00000566'}, {'symbol': 'CVCETH', 'price': '0.00000000'}, {'symbol': 'CVCBNB', 'price': '0.00000000'}, {'symbol': 'THETABTC', 'price': '0.00000265'}, {'symbol': 'THETAETH', 'price': '0.00050170'}, {'symbol': 'THETABNB', 'price': '0.00273600'}, {'symbol': 'XRPBNB', 'price': '0.00227570'}, {'symbol': 'TUSDUSDT', 'price': '0.99930000'}, {'symbol': 'IOTAUSDT', 'price': '0.05640000'}, {'symbol': 'XLMUSDT', 'price': '0.16060000'}, {'symbol': 'IOTXBTC', 'price': '0.00000009'}, {'symbol': 'IOTXETH', 'price': '0.00000300'}, {'symbol': 'QKCBTC', 'price': '0.00000010'}, {'symbol': 'QKCETH', 'price': '0.00000430'}, {'symbol': 'AGIBTC', 'price': '0.00000000'}, {'symbol': 'AGIETH', 'price': '0.00000000'}, {'symbol': 'AGIBNB', 'price': '0.00000000'}, {'symbol': 'NXSBTC', 'price': '0.00000000'}, {'symbol': 'NXSETH', 'price': '0.00000000'}, {'symbol': 'NXSBNB', 'price': '0.00000000'}, {'symbol': 'ENJBNB', 'price': '0.00136800'}, {'symbol': 'DATABTC', 'price': '0.00000008'}, {'symbol': 'DATAETH', 'price': '0.00002034'}, {'symbol': 'ONTUSDT', 'price': '0.07412000'}, {'symbol': 'TRXBNB', 'price': '0.00053030'}, {'symbol': 'TRXUSDT', 'price': '0.32680000'}, {'symbol': 'ETCUSDT', 'price': '8.47000000'}, {'symbol': 'ETCBNB', 'price': '0.01416000'}, {'symbol': 'ICXUSDT', 'price': '0.03860000'}, {'symbol': 'SCBTC', 'price': '0.00000000'}, {'symbol': 'SCETH', 'price': '0.00000049'}, {'symbol': 'NPXSBTC', 'price': '0.00000000'}, {'symbol': 'NPXSETH', 'price': '0.00000000'}, {'symbol': 'VENUSDT', 'price': '0.00000000'}, {'symbol': 'KEYBTC', 'price': '0.00000000'}, {'symbol': 'KEYETH', 'price': '0.00000227'}, {'symbol': 'NASBTC', 'price': '0.00000000'}, {'symbol': 'NASETH', 'price': '0.00000000'}, {'symbol': 'NASBNB', 'price': '0.00000000'}, {'symbol': 'MFTBTC', 'price': '0.00000000'}, {'symbol': 'MFTETH', 'price': '0.00000433'}, {'symbol': 'MFTBNB', 'price': '0.00000000'}, {'symbol': 'DENTBTC', 'price': '0.00000000'}, {'symbol': 'DENTETH', 'price': '0.00000007'}, {'symbol': 'ARDRBTC', 'price': '0.00000065'}, {'symbol': 'ARDRETH', 'price': '0.00000000'}, {'symbol': 'ARDRBNB', 'price': '0.00000000'}, {'symbol': 'NULSUSDT', 'price': '0.02580000'}, {'symbol': 'HOTBTC', 'price': '0.00000000'}, {'symbol': 'HOTETH', 'price': '0.00000017'}, {'symbol': 'VETBTC', 'price': '0.00000009'}, {'symbol': 'VETETH', 'price': '0.00000344'}, {'symbol': 'VETUSDT', 'price': '0.00712200'}, {'symbol': 'VETBNB', 'price': '0.00001339'}, {'symbol': 'DOCKBTC', 'price': '0.00000005'}, {'symbol': 'DOCKETH', 'price': '0.00000000'}, {'symbol': 'POLYBTC', 'price': '0.00001384'}, {'symbol': 'POLYBNB', 'price': '0.00000000'}, {'symbol': 'PHXBTC', 'price': '0.00000000'}, {'symbol': 'PHXETH', 'price': '0.00000000'}, {'symbol': 'PHXBNB', 'price': '0.00000000'}, {'symbol': 'HCBTC', 'price': '0.00000000'}, {'symbol': 'HCETH', 'price': '0.00000000'}, {'symbol': 'GOBTC', 'price': '0.00000000'}, {'symbol': 'GOBNB', 'price': '0.00000000'}, {'symbol': 'PAXBTC', 'price': '0.00000000'}, {'symbol': 'PAXBNB', 'price': '0.00000000'}, {'symbol': 'PAXUSDT', 'price': '0.00000000'}, {'symbol': 'PAXETH', 'price': '0.00000000'}, {'symbol': 'RVNBTC', 'price': '0.00000010'}, {'symbol': 'DCRBTC', 'price': '0.00021850'}, {'symbol': 'DCRBNB', 'price': '0.00000000'}, {'symbol': 'USDCBNB', 'price': '0.00000000'}, {'symbol': 'MITHBTC', 'price': '0.00000080'}, {'symbol': 'MITHBNB', 'price': '0.00004410'}, {'symbol': 'BCHABCBTC', 'price': '0.00000000'}, {'symbol': 'BCHSVBTC', 'price': '0.00000000'}, {'symbol': 'BCHABCUSDT', 'price': '0.00000000'}, {'symbol': 'BCHSVUSDT', 'price': '0.00000000'}, {'symbol': 'BNBPAX', 'price': '0.00000000'}, {'symbol': 'BTCPAX', 'price': '0.00000000'}, {'symbol': 'ETHPAX', 'price': '0.00000000'}, {'symbol': 'XRPPAX', 'price': '0.00000000'}, {'symbol': 'EOSPAX', 'price': '0.00000000'}, {'symbol': 'XLMPAX', 'price': '0.00000000'}, {'symbol': 'RENBTC', 'price': '0.00000043'}, {'symbol': 'RENBNB', 'price': '0.00000000'}, {'symbol': 'BNBTUSD', 'price': '605.48000000'}, {'symbol': 'XRPTUSD', 'price': '1.31780000'}, {'symbol': 'EOSTUSD', 'price': '0.00000000'}, {'symbol': 'XLMTUSD', 'price': '0.00000000'}, {'symbol': 'BNBUSDC', 'price': '616.97000000'}, {'symbol': 'BTCUSDC', 'price': '73660.97000000'}, {'symbol': 'ETHUSDC', 'price': '2303.12000000'}, {'symbol': 'XRPUSDC', 'price': '1.40380000'}, {'symbol': 'EOSUSDC', 'price': '0.77780000'}, {'symbol': 'XLMUSDC', 'price': '0.16070000'}, {'symbol': 'USDCUSDT', 'price': '0.99973000'}, {'symbol': 'ADATUSD', 'price': '0.38470000'}, {'symbol': 'TRXTUSD', 'price': '0.05986000'}, {'symbol': 'NEOTUSD', 'price': '0.00000000'}, {'symbol': 'TRXXRP', 'price': '0.23310000'}, {'symbol': 'XZCXRP', 'price': '0.00000000'}, {'symbol': 'PAXTUSD', 'price': '0.00000000'}, {'symbol': 'USDCTUSD', 'price': '0.00000000'}, {'symbol': 'USDCPAX', 'price': '0.00000000'}, {'symbol': 'LINKUSDT', 'price': '9.21000000'}, {'symbol': 'LINKTUSD', 'price': '14.42300000'}, {'symbol': 'LINKPAX', 'price': '0.00000000'}, {'symbol': 'LINKUSDC', 'price': '9.22000000'}, {'symbol': 'WAVESUSDT', 'price': '1.07600000'}, {'symbol': 'WAVESTUSD', 'price': '0.00000000'}, {'symbol': 'WAVESPAX', 'price': '0.00000000'}, {'symbol': 'WAVESUSDC', 'price': '0.00000000'}, {'symbo

In [42]:
prices

[{'symbol': 'ETHBTC', 'price': '0.03127000'},
 {'symbol': 'LTCBTC', 'price': '0.00074600'},
 {'symbol': 'BNBBTC', 'price': '0.00837200'},
 {'symbol': 'NEOBTC', 'price': '0.00003952'},
 {'symbol': 'QTUMETH', 'price': '0.00046550'},
 {'symbol': 'EOSETH', 'price': '0.00030670'},
 {'symbol': 'SNTETH', 'price': '0.00001700'},
 {'symbol': 'BNTETH', 'price': '0.00020260'},
 {'symbol': 'BCCBTC', 'price': '0.00000000'},
 {'symbol': 'GASBTC', 'price': '0.00002350'},
 {'symbol': 'BNBETH', 'price': '0.26770000'},
 {'symbol': 'BTCUSDT', 'price': '73644.49000000'},
 {'symbol': 'ETHUSDT', 'price': '2302.76000000'},
 {'symbol': 'HSRBTC', 'price': '0.00000000'},
 {'symbol': 'OAXETH', 'price': '0.00000000'},
 {'symbol': 'DNTETH', 'price': '0.00000000'},
 {'symbol': 'MCOETH', 'price': '0.00000000'},
 {'symbol': 'ICNETH', 'price': '0.00000000'},
 {'symbol': 'MCOBTC', 'price': '0.00000000'},
 {'symbol': 'WTCBTC', 'price': '0.00000024'},
 {'symbol': 'WTCETH', 'price': '0.00000000'},
 {'symbol': 'LRCBTC', 'price': '0.00000052'},
 {'symbol': 'LRCETH', 'price': '0.00001675'},
 {'symbol': 'QTUMBTC', 'price': '0.00001628'},
 {'symbol': 'YOYOBTC', 'price': '0.00000000'},
 {'symbol': 'OMGBTC', 'price': '0.00003080'},
 {'symbol': 'OMGETH', 'price': '0.00079100'},
 {'symbol': 'ZRXBTC', 'price': '0.00000154'},
 {'symbol': 'ZRXETH', 'price': '0.00009940'},
 {'symbol': 'STRATBTC', 'price': '0.00000000'},
 {'symbol': 'STRATETH', 'price': '0.00000000'},
 {'symbol': 'SNGLSBTC', 'price': '0.00000000'},
 {'symbol': 'SNGLSETH', 'price': '0.00000000'},
 {'symbol': 'BQXBTC', 'price': '0.00000000'},
 {'symbol': 'BQXETH', 'price': '0.00000000'},
 {'symbol': 'KNCBTC', 'price': '0.00000185'},
 {'symbol': 'KNCETH', 'price': '0.00039410'},
 {'symbol': 'FUNBTC', 'price': '0.00000000'},
 {'symbol': 'FUNETH', 'price': '0.00000146'},
 {'symbol': 'SNMBTC', 'price': '0.00000057'},
 {'symbol': 'SNMETH', 'price': '0.00000000'},
 {'symbol': 'NEOETH', 'price': '0.00477500'},
 {'symbol': 'IOTABTC', 'price': '0.00000076'},
 {'symbol': 'IOTAETH', 'price': '0.00003346'},
 {'symbol': 'LINKBTC', 'price': '0.00012510'},
 {'symbol': 'LINKETH', 'price': '0.00400300'},
 {'symbol': 'XVGBTC', 'price': '0.00000000'},
 {'symbol': 'XVGETH', 'price': '0.00000247'},
 {'symbol': 'SALTBTC', 'price': '0.00000000'},
 {'symbol': 'SALTETH', 'price': '0.00000000'},
 {'symbol': 'MDABTC', 'price': '0.00000000'},
 {'symbol': 'MDAETH', 'price': '0.00000000'},
 {'symbol': 'MTLBTC', 'price': '0.00000405'},
 {'symbol': 'MTLETH', 'price': '0.00068340'},
 {'symbol': 'SUBBTC', 'price': '0.00000000'},
 {'symbol': 'SUBETH', 'price': '0.00000000'},
 {'symbol': 'EOSBTC', 'price': '0.00000716'},
 {'symbol': 'SNTBTC', 'price': '0.00000032'},
 {'symbol': 'ETCETH', 'price': '0.00387000'},
 {'symbol': 'ETCBTC', 'price': '0.00011520'},
 {'symbol': 'MTHBTC', 'price': '0.00000000'},
 {'symbol': 'MTHETH', 'price': '0.00000000'},
 {'symbol': 'ENGBTC', 'price': '0.00000000'},
 {'symbol': 'ENGETH', 'price': '0.00000000'},
 {'symbol': 'DNTBTC', 'price': '0.00000186'},
 {'symbol': 'ZECBTC', 'price': '0.00463620'},
 {'symbol': 'ZECETH', 'price': '0.14828000'},
 {'symbol': 'BNTBTC', 'price': '0.00000794'},
 {'symbol': 'ASTBTC', 'price': '0.00000124'},
 {'symbol': 'ASTETH', 'price': '0.00000000'},
 {'symbol': 'DASHBTC', 'price': '0.00050420'},
 {'symbol': 'DASHETH', 'price': '0.02084000'},
 {'symbol': 'OAXBTC', 'price': '0.00000038'},
 {'symbol': 'ICNBTC', 'price': '0.00000000'},
 {'symbol': 'BTGBTC', 'price': '0.00091300'},
 {'symbol': 'BTGETH', 'price': '0.00000000'},
 {'symbol': 'EVXBTC', 'price': '0.00000000'},
 {'symbol': 'EVXETH', 'price': '0.00000000'},
 {'symbol': 'REQBTC', 'price': '0.00000112'},
 {'symbol': 'REQETH', 'price': '0.00000000'},
 {'symbol': 'VIBBTC', 'price': '0.00000051'},
 {'symbol': 'VIBETH', 'price': '0.00003450'},
 {'symbol': 'HSRETH', 'price': '0.00000000'},
 {'symbol': 'TRXBTC', 'price': '0.00000443'},
 {'symbol': 'TRXETH', 'price': '0.00014163'},
 {'symbol': 'POWRBTC', 'price': '0.00000094'},
 {'symbol': 'POWRETH', 'price': '0.00002760'},
 {'symbol': 'ARKBTC', 'price': '0.00001679'},
 {'symbol': 'ARKETH', 'price': '0.00000000'},
 {'symbol': 'YOYOETH', 'price': '0.00000000'},
 {'symbol': 'XRPBTC', 'price': '0.00001906'},
 {'symbol': 'XRPETH', 'price': '0.00060920'},
 {'symbol': 'MODBTC', 'price': '0.00000000'},
 {'symbol': 'MODETH', 'price': '0.00000000'},
 {'symbol': 'ENJBTC', 'price': '0.00000035'},
 {'symbol': 'ENJETH', 'price': '0.00006172'},
 {'symbol': 'STORJBTC', 'price': '0.00000143'},
 {'symbol': 'STORJETH', 'price': '0.00000000'},
 {'symbol': 'BNBUSDT', 'price': '616.74000000'},
 {'symbol': 'VENBNB', 'price': '0.00000000'},
 {'symbol': 'YOYOBNB', 'price': '0.00000000'},
 {'symbol': 'POWRBNB', 'price': '0.00000000'},
 {'symbol': 'VENBTC', 'price': '0.00000000'},
 {'symbol': 'VENETH', 'price': '0.00000000'},
 {'symbol': 'KMDBTC', 'price': '0.00000015'},
 {'symbol': 'KMDETH', 'price': '0.00000000'},
 {'symbol': 'NULSBNB', 'price': '0.00000000'},
 {'symbol': 'RCNBTC', 'price': '0.00000000'},
 {'symbol': 'RCNETH', 'price': '0.00000000'},
 {'symbol': 'RCNBNB', 'price': '0.00000000'},
 {'symbol': 'NULSBTC', 'price': '0.00000030'},
 {'symbol': 'NULSETH', 'price': '0.00000000'},
 {'symbol': 'RDNBTC', 'price': '0.00000000'},
 {'symbol': 'RDNETH', 'price': '0.00000000'},
 {'symbol': 'RDNBNB', 'price': '0.00000000'},
 {'symbol': 'XMRBTC', 'price': '0.00228700'},
 {'symbol': 'XMRETH', 'price': '0.04032000'},
 {'symbol': 'DLTBNB', 'price': '0.00000000'},
 {'symbol': 'WTCBNB', 'price': '0.00000000'},
 {'symbol': 'DLTBTC', 'price': '0.00000000'},
 {'symbol': 'DLTETH', 'price': '0.00000000'},
 {'symbol': 'AMBBTC', 'price': '0.00000010'},
 {'symbol': 'AMBETH', 'price': '0.00000000'},
 {'symbol': 'AMBBNB', 'price': '0.00000000'},
 {'symbol': 'BCCETH', 'price': '0.00000000'},
 {'symbol': 'BCCUSDT', 'price': '0.00000000'},
 {'symbol': 'BCCBNB', 'price': '0.00000000'},
 {'symbol': 'BATBTC', 'price': '0.00000136'},
 {'symbol': 'BATETH', 'price': '0.00010630'},
 {'symbol': 'BATBNB', 'price': '0.00000000'},
 {'symbol': 'BCPTBTC', 'price': '0.00000000'},
 {'symbol': 'BCPTETH', 'price': '0.00000000'},
 {'symbol': 'BCPTBNB', 'price': '0.00000000'},
 {'symbol': 'ARNBTC', 'price': '0.00000000'},
 {'symbol': 'ARNETH', 'price': '0.00000000'},
 {'symbol': 'GVTBTC', 'price': '0.00000000'},
 {'symbol': 'GVTETH', 'price': '0.00000000'},
 {'symbol': 'CDTBTC', 'price': '0.00000000'},
 {'symbol': 'CDTETH', 'price': '0.00000000'},
 {'symbol': 'GXSBTC', 'price': '0.00000000'},
 {'symbol': 'GXSETH', 'price': '0.00000000'},
 {'symbol': 'NEOUSDT', 'price': '2.90000000'},
 {'symbol': 'NEOBNB', 'price': '0.03836000'},
 {'symbol': 'POEBTC', 'price': '0.00000000'},
 {'symbol': 'POEETH', 'price': '0.00000000'},
 {'symbol': 'QSPBTC', 'price': '0.00000000'},
 {'symbol': 'QSPETH', 'price': '0.00000000'},
 {'symbol': 'QSPBNB', 'price': '0.00000000'},
 {'symbol': 'BTSBTC', 'price': '0.00000043'},
 {'symbol': 'BTSETH', 'price': '0.00000000'},
 {'symbol': 'BTSBNB', 'price': '0.00000000'},
 {'symbol': 'XZCBTC', 'price': '0.00000000'},
 {'symbol': 'XZCETH', 'price': '0.00000000'},
 {'symbol': 'XZCBNB', 'price': '0.00000000'},
 {'symbol': 'LSKBTC', 'price': '0.00000186'},
 {'symbol': 'LSKETH', 'price': '0.00033730'},
 {'symbol': 'LSKBNB', 'price': '0.00000000'},
 {'symbol': 'TNTBTC', 'price': '0.00000000'},
 {'symbol': 'TNTETH', 'price': '0.00000000'},
 {'symbol': 'FUELBTC', 'price': '0.00000000'},
 {'symbol': 'FUELETH', 'price': '0.00000000'},
 {'symbol': 'MANABTC', 'price': '0.00000147'},
 {'symbol': 'MANAETH', 'price': '0.00004950'},
 {'symbol': 'BCDBTC', 'price': '0.00000000'},
 {'symbol': 'BCDETH', 'price': '0.00000000'},
 {'symbol': 'DGDBTC', 'price': '0.00000000'},
 {'symbol': 'DGDETH', 'price': '0.00000000'},
 {'symbol': 'IOTABNB', 'price': '0.00071700'},
 {'symbol': 'ADXBTC', 'price': '0.00000105'},
 {'symbol': 'ADXETH', 'price': '0.00003007'},
 {'symbol': 'ADXBNB', 'price': '0.00000000'},
 {'symbol': 'ADABTC', 'price': '0.00000337'},
 {'symbol': 'ADAETH', 'price': '0.00010790'},
 {'symbol': 'PPTBTC', 'price': '0.00000000'},
 {'symbol': 'PPTETH', 'price': '0.00000000'},
 {'symbol': 'CMTBTC', 'price': '0.00000000'},
 {'symbol': 'CMTETH', 'price': '0.00000000'},
 {'symbol': 'CMTBNB', 'price': '0.00000000'},
 {'symbol': 'XLMBTC', 'price': '0.00000218'},
 {'symbol': 'XLMETH', 'price': '0.00006992'},
 {'symbol': 'XLMBNB', 'price': '0.00030360'},
 {'symbol': 'CNDBTC', 'price': '0.00000000'},
 {'symbol': 'CNDETH', 'price': '0.00000000'},
 {'symbol': 'CNDBNB', 'price': '0.00000000'},
 {'symbol': 'LENDBTC', 'price': '0.00000000'},
 {'symbol': 'LENDETH', 'price': '0.00000000'},
 {'symbol': 'WABIBTC', 'price': '0.00000030'},
 {'symbol': 'WABIETH', 'price': '0.00000000'},
 {'symbol': 'WABIBNB', 'price': '0.00000000'},
 {'symbol': 'LTCETH', 'price': '0.02392000'},
 {'symbol': 'LTCUSDT', 'price': '54.96000000'},
 {'symbol': 'LTCBNB', 'price': '0.08920000'},
 {'symbol': 'TNBBTC', 'price': '0.00000000'},
 {'symbol': 'TNBETH', 'price': '0.00000000'},
 {'symbol': 'WAVESBTC', 'price': '0.00001626'},
 {'symbol': 'WAVESETH', 'price': '0.00029800'},
 {'symbol': 'WAVESBNB', 'price': '0.00513000'},
 {'symbol': 'GTOBTC', 'price': '0.00000077'},
 {'symbol': 'GTOETH', 'price': '0.00000000'},
 {'symbol': 'GTOBNB', 'price': '0.00000000'},
 {'symbol': 'ICXBTC', 'price': '0.00000056'},
 {'symbol': 'ICXETH', 'price': '0.00011790'},
 {'symbol': 'ICXBNB', 'price': '0.00000000'},
 {'symbol': 'OSTBTC', 'price': '0.00000000'},
 {'symbol': 'OSTETH', 'price': '0.00000000'},
 {'symbol': 'OSTBNB', 'price': '0.00000000'},
 {'symbol': 'ELFBTC', 'price': '0.00000274'},
 {'symbol': 'ELFETH', 'price': '0.00014330'},
 {'symbol': 'AIONBTC', 'price': '0.00000139'},
 {'symbol': 'AIONETH', 'price': '0.00000000'},
 {'symbol': 'AIONBNB', 'price': '0.00000000'},
 {'symbol': 'NEBLBTC', 'price': '0.00001200'},
 {'symbol': 'NEBLBNB', 'price': '0.00000000'},
 {'symbol': 'BRDBTC', 'price': '0.00000000'},
 {'symbol': 'BRDETH', 'price': '0.00000000'},
 {'symbol': 'BRDBNB', 'price': '0.00000000'},
 {'symbol': 'MCOBNB', 'price': '0.00000000'},
 {'symbol': 'EDOBTC', 'price': '0.00000000'},
 {'symbol': 'EDOETH', 'price': '0.00000000'},
 {'symbol': 'WINGSBTC', 'price': '0.00000000'},
 {'symbol': 'WINGSETH', 'price': '0.00000000'},
 {'symbol': 'NAVBTC', 'price': '0.00000000'},
 {'symbol': 'NAVETH', 'price': '0.00000000'},
 {'symbol': 'NAVBNB', 'price': '0.00000000'},
 {'symbol': 'LUNBTC', 'price': '0.00000000'},
 {'symbol': 'LUNETH', 'price': '0.00000000'},
 {'symbol': 'TRIGBTC', 'price': '0.00000000'},
 {'symbol': 'TRIGETH', 'price': '0.00000000'},
 {'symbol': 'TRIGBNB', 'price': '0.00000000'},
 {'symbol': 'APPCBTC', 'price': '0.00000000'},
 {'symbol': 'APPCETH', 'price': '0.00000000'},
 {'symbol': 'APPCBNB', 'price': '0.00000000'},
 {'symbol': 'VIBEBTC', 'price': '0.00000000'},
 {'symbol': 'VIBEETH', 'price': '0.00000000'},
 {'symbol': 'RLCBTC', 'price': '0.00000553'},
 {'symbol': 'RLCETH', 'price': '0.00018420'},
 {'symbol': 'RLCBNB', 'price': '0.00000000'},
 {'symbol': 'INSBTC', 'price': '0.00000000'},
 {'symbol': 'INSETH', 'price': '0.00000000'},
 {'symbol': 'PIVXBTC', 'price': '0.00000147'},
 {'symbol': 'PIVXBNB', 'price': '0.00000000'},
 {'symbol': 'IOSTBTC', 'price': '0.00000010'},
 {'symbol': 'IOSTETH', 'price': '0.00000372'},
 {'symbol': 'CHATBTC', 'price': '0.00000000'},
 {'symbol': 'CHATETH', 'price': '0.00000000'},
 {'symbol': 'STEEMBTC', 'price': '0.00000079'},
 {'symbol': 'STEEMETH', 'price': '0.00002531'},
 {'symbol': 'STEEMBNB', 'price': '0.00000000'},
 {'symbol': 'NANOBTC', 'price': '0.00000000'},
 {'symbol': 'NANOETH', 'price': '0.00000000'},
 {'symbol': 'NANOBNB', 'price': '0.00000000'},
 {'symbol': 'VIABTC', 'price': '0.00000000'},
 {'symbol': 'VIAETH', 'price': '0.00000000'},
 {'symbol': 'VIABNB', 'price': '0.00000000'},
 {'symbol': 'BLZBTC', 'price': '0.00000060'},
 {'symbol': 'BLZETH', 'price': '0.00004159'},
 {'symbol': 'BLZBNB', 'price': '0.00000000'},
 {'symbol': 'AEBTC', 'price': '0.00000000'},
 {'symbol': 'AEETH', 'price': '0.00000000'},
 {'symbol': 'AEBNB', 'price': '0.00000000'},
 {'symbol': 'RPXBTC', 'price': '0.00000000'},
 {'symbol': 'RPXETH', 'price': '0.00000000'},
 {'symbol': 'RPXBNB', 'price': '0.00000000'},
 {'symbol': 'NCASHBTC', 'price': '0.00000000'},
 {'symbol': 'NCASHETH', 'price': '0.00000000'},
 {'symbol': 'NCASHBNB', 'price': '0.00000000'},
 {'symbol': 'POABTC', 'price': '0.00000000'},
 {'symbol': 'POAETH', 'price': '0.00000000'},
 {'symbol': 'POABNB', 'price': '0.00000000'},
 {'symbol': 'ZILBTC', 'price': '0.00000010'},
 {'symbol': 'ZILETH', 'price': '0.00000168'},
 {'symbol': 'ZILBNB', 'price': '0.00008858'},
 {'symbol': 'ONTBTC', 'price': '0.00000101'},
 {'symbol': 'ONTETH', 'price': '0.00012530'},
 {'symbol': 'ONTBNB', 'price': '0.00000000'},
 {'symbol': 'STORMBTC', 'price': '0.00000000'},
 {'symbol': 'STORMETH', 'price': '0.00000000'},
 {'symbol': 'STORMBNB', 'price': '0.00000000'},
 {'symbol': 'QTUMBNB', 'price': '0.00000000'},
 {'symbol': 'QTUMUSDT', 'price': '0.91800000'},
 {'symbol': 'XEMBTC', 'price': '0.00000192'},
 {'symbol': 'XEMETH', 'price': '0.00000000'},
 {'symbol': 'XEMBNB', 'price': '0.00000000'},
 {'symbol': 'WANBTC', 'price': '0.00000076'},
 {'symbol': 'WANETH', 'price': '0.00009270'},
 {'symbol': 'WANBNB', 'price': '0.00000000'},
 {'symbol': 'WPRBTC', 'price': '0.00000000'},
 {'symbol': 'WPRETH', 'price': '0.00000000'},
 {'symbol': 'QLCBTC', 'price': '0.00000021'},
 {'symbol': 'QLCETH', 'price': '0.00000000'},
 {'symbol': 'SYSBTC', 'price': '0.00000019'},
 {'symbol': 'SYSETH', 'price': '0.00000000'},
 {'symbol': 'SYSBNB', 'price': '0.00000000'},
 {'symbol': 'QLCBNB', 'price': '0.00000000'},
 {'symbol': 'GRSBTC', 'price': '0.00000000'},
 {'symbol': 'GRSETH', 'price': '0.00000000'},
 {'symbol': 'ADAUSDT', 'price': '0.24820000'},
 {'symbol': 'ADABNB', 'price': '0.00040300'},
 {'symbol': 'CLOAKBTC', 'price': '0.00000000'},
 {'symbol': 'CLOAKETH', 'price': '0.00000000'},
 {'symbol': 'GNTBTC', 'price': '0.00000000'},
 {'symbol': 'GNTETH', 'price': '0.00000000'},
 {'symbol': 'GNTBNB', 'price': '0.00000000'},
 {'symbol': 'LOOMBTC', 'price': '0.00000075'},
 {'symbol': 'LOOMETH', 'price': '0.00003231'},
 {'symbol': 'LOOMBNB', 'price': '0.00000000'},
 {'symbol': 'XRPUSDT', 'price': '1.40350000'},
 {'symbol': 'BCNBTC', 'price': '0.00000000'},
 {'symbol': 'BCNETH', 'price': '0.00000000'},
 {'symbol': 'BCNBNB', 'price': '0.00000000'},
 {'symbol': 'REPBTC', 'price': '0.00034130'},
 {'symbol': 'REPBNB', 'price': '0.00000000'},
 {'symbol': 'BTCTUSD', 'price': '73469.60000000'},
 {'symbol': 'TUSDBTC', 'price': '0.00000000'},
 {'symbol': 'ETHTUSD', 'price': '2303.47000000'},
 {'symbol': 'TUSDETH', 'price': '0.00000000'},
 {'symbol': 'TUSDBNB', 'price': '0.00000000'},
 {'symbol': 'ZENBTC', 'price': '0.00007848'},
 {'symbol': 'ZENETH', 'price': '0.00399100'},
 {'symbol': 'ZENBNB', 'price': '0.03290000'},
 {'symbol': 'SKYCOINBTC', 'price': '0.00000000'},
 {'symbol': 'SKYCOINETH', 'price': '0.00000000'},
 {'symbol': 'SKYCOINBNB', 'price': '0.00000000'},
 {'symbol': 'EOSUSDT', 'price': '0.77990000'},
 {'symbol': 'EOSBNB', 'price': '0.00258300'},
 {'symbol': 'CVCBTC', 'price': '0.00000566'},
 {'symbol': 'CVCETH', 'price': '0.00000000'},
 {'symbol': 'CVCBNB', 'price': '0.00000000'},
 {'symbol': 'THETABTC', 'price': '0.00000265'},
 {'symbol': 'THETAETH', 'price': '0.00050170'},
 {'symbol': 'THETABNB', 'price': '0.00273600'},
 {'symbol': 'XRPBNB', 'price': '0.00227570'},
 {'symbol': 'TUSDUSDT', 'price': '0.99930000'},
 {'symbol': 'IOTAUSDT', 'price': '0.05640000'},
 {'symbol': 'XLMUSDT', 'price': '0.16060000'},
 {'symbol': 'IOTXBTC', 'price': '0.00000009'},
 {'symbol': 'IOTXETH', 'price': '0.00000300'},
 {'symbol': 'QKCBTC', 'price': '0.00000010'},
 {'symbol': 'QKCETH', 'price': '0.00000430'},
 {'symbol': 'AGIBTC', 'price': '0.00000000'},
 {'symbol': 'AGIETH', 'price': '0.00000000'},
 {'symbol': 'AGIBNB', 'price': '0.00000000'},
 {'symbol': 'NXSBTC', 'price': '0.00000000'},
 {'symbol': 'NXSETH', 'price': '0.00000000'},
 {'symbol': 'NXSBNB', 'price': '0.00000000'},
 {'symbol': 'ENJBNB', 'price': '0.00136800'},
 {'symbol': 'DATABTC', 'price': '0.00000008'},
 {'symbol': 'DATAETH', 'price': '0.00002034'},
 {'symbol': 'ONTUSDT', 'price': '0.07412000'},
 {'symbol': 'TRXBNB', 'price': '0.00053030'},
 {'symbol': 'TRXUSDT', 'price': '0.32680000'},
 {'symbol': 'ETCUSDT', 'price': '8.47000000'},
 {'symbol': 'ETCBNB', 'price': '0.01416000'},
 {'symbol': 'ICXUSDT', 'price': '0.03860000'},
 {'symbol': 'SCBTC', 'price': '0.00000000'},
 {'symbol': 'SCETH', 'price': '0.00000049'},
 {'symbol': 'NPXSBTC', 'price': '0.00000000'},
 {'symbol': 'NPXSETH', 'price': '0.00000000'},
 {'symbol': 'VENUSDT', 'price': '0.00000000'},
 {'symbol': 'KEYBTC', 'price': '0.00000000'},
 {'symbol': 'KEYETH', 'price': '0.00000227'},
 {'symbol': 'NASBTC', 'price': '0.00000000'},
 {'symbol': 'NASETH', 'price': '0.00000000'},
 {'symbol': 'NASBNB', 'price': '0.00000000'},
 {'symbol': 'MFTBTC', 'price': '0.00000000'},
 {'symbol': 'MFTETH', 'price': '0.00000433'},
 {'symbol': 'MFTBNB', 'price': '0.00000000'},
 {'symbol': 'DENTBTC', 'price': '0.00000000'},
 {'symbol': 'DENTETH', 'price': '0.00000007'},
 {'symbol': 'ARDRBTC', 'price': '0.00000065'},
 {'symbol': 'ARDRETH', 'price': '0.00000000'},
 {'symbol': 'ARDRBNB', 'price': '0.00000000'},
 {'symbol': 'NULSUSDT', 'price': '0.02580000'},
 {'symbol': 'HOTBTC', 'price': '0.00000000'},
 {'symbol': 'HOTETH', 'price': '0.00000017'},
 {'symbol': 'VETBTC', 'price': '0.00000009'},
 {'symbol': 'VETETH', 'price': '0.00000344'},
 {'symbol': 'VETUSDT', 'price': '0.00712200'},
 {'symbol': 'VETBNB', 'price': '0.00001339'},
 {'symbol': 'DOCKBTC', 'price': '0.00000005'},
 {'symbol': 'DOCKETH', 'price': '0.00000000'},
 {'symbol': 'POLYBTC', 'price': '0.00001384'},
 {'symbol': 'POLYBNB', 'price': '0.00000000'},
 {'symbol': 'PHXBTC', 'price': '0.00000000'},
 {'symbol': 'PHXETH', 'price': '0.00000000'},
 {'symbol': 'PHXBNB', 'price': '0.00000000'},
 {'symbol': 'HCBTC', 'price': '0.00000000'},
 {'symbol': 'HCETH', 'price': '0.00000000'},
 {'symbol': 'GOBTC', 'price': '0.00000000'},
 {'symbol': 'GOBNB', 'price': '0.00000000'},
 {'symbol': 'PAXBTC', 'price': '0.00000000'},
 {'symbol': 'PAXBNB', 'price': '0.00000000'},
 {'symbol': 'PAXUSDT', 'price': '0.00000000'},
 {'symbol': 'PAXETH', 'price': '0.00000000'},
 {'symbol': 'RVNBTC', 'price': '0.00000010'},
 {'symbol': 'DCRBTC', 'price': '0.00021850'},
 {'symbol': 'DCRBNB', 'price': '0.00000000'},
 {'symbol': 'USDCBNB', 'price': '0.00000000'},
 {'symbol': 'MITHBTC', 'price': '0.00000080'},
 {'symbol': 'MITHBNB', 'price': '0.00004410'},
 {'symbol': 'BCHABCBTC', 'price': '0.00000000'},
 {'symbol': 'BCHSVBTC', 'price': '0.00000000'},
 {'symbol': 'BCHABCUSDT', 'price': '0.00000000'},
 {'symbol': 'BCHSVUSDT', 'price': '0.00000000'},
 {'symbol': 'BNBPAX', 'price': '0.00000000'},
 {'symbol': 'BTCPAX', 'price': '0.00000000'},
 {'symbol': 'ETHPAX', 'price': '0.00000000'},
 {'symbol': 'XRPPAX', 'price': '0.00000000'},
 {'symbol': 'EOSPAX', 'price': '0.00000000'},
 {'symbol': 'XLMPAX', 'price': '0.00000000'},
 {'symbol': 'RENBTC', 'price': '0.00000043'},
 {'symbol': 'RENBNB', 'price': '0.00000000'},
 {'symbol': 'BNBTUSD', 'price': '605.48000000'},
 {'symbol': 'XRPTUSD', 'price': '1.31780000'},
 {'symbol': 'EOSTUSD', 'price': '0.00000000'},
 {'symbol': 'XLMTUSD', 'price': '0.00000000'},
 {'symbol': 'BNBUSDC', 'price': '616.97000000'},
 {'symbol': 'BTCUSDC', 'price': '73660.97000000'},
 {'symbol': 'ETHUSDC', 'price': '2303.12000000'},
 {'symbol': 'XRPUSDC', 'price': '1.40380000'},
 {'symbol': 'EOSUSDC', 'price': '0.77780000'},
 {'symbol': 'XLMUSDC', 'price': '0.16070000'},
 {'symbol': 'USDCUSDT', 'price': '0.99973000'},
 {'symbol': 'ADATUSD', 'price': '0.38470000'},
 {'symbol': 'TRXTUSD', 'price': '0.05986000'},
 {'symbol': 'NEOTUSD', 'price': '0.00000000'},
 {'symbol': 'TRXXRP', 'price': '0.23310000'},
 {'symbol': 'XZCXRP', 'price': '0.00000000'},
 {'symbol': 'PAXTUSD', 'price': '0.00000000'},
 {'symbol': 'USDCTUSD', 'price': '0.00000000'},

In [34]:
def get_trades():
    resp = req.get(trades)
    resp.raise_for_status()

    data = resp.json()
    print(data)

In [35]:
get_trades()

[{'id': 528079401, 'price': '0.03127000', 'qty': '0.12850000', 'quoteQty': '0.00401819', 'time': 1776348129731, 'isBuyerMaker': False, 'isBestMatch': True}, {'id': 528079402, 'price': '0.03127000', 'qty': '0.25920000', 'quoteQty': '0.00810518', 'time': 1776348133002, 'isBuyerMaker': False, 'isBestMatch': True}, {'id': 528079403, 'price': '0.03127000', 'qty': '0.00340000', 'quoteQty': '0.00010631', 'time': 1776348133002, 'isBuyerMaker': False, 'isBestMatch': True}, {'id': 528079404, 'price': '0.03127000', 'qty': '0.59460000', 'quoteQty': '0.01859314', 'time': 1776348133002, 'isBuyerMaker': False, 'isBestMatch': True}, {'id': 528079405, 'price': '0.03127000', 'qty': '0.05940000', 'quoteQty': '0.00185743', 'time': 1776348134735, 'isBuyerMaker': False, 'isBestMatch': True}]

In [45]:
def order_book():
    res = req.get('https://api.binance.com/api/v3/depth?symbol=BTCUSDT&limit=5')
    res.raise_for_status()

    data = res.json()
    print(data)

In [46]:
order_book()

{'lastUpdateId': 92100381924, 'bids': [['73600.43000000', '3.99205000'], ['73600.36000000', '0.00020000'], ['73600.35000000', '0.08351000'], ['73600.32000000', '0.00016000'], ['73600.25000000', '0.30262000']], 'asks': [['73600.44000000', '0.00214000'], ['73600.45000000', '0.00063000'], ['73600.46000000', '0.00011000'], ['73600.75000000', '0.00023000'], ['73600.76000000', '0.02190000']]}

In [47]:
def klines():
    res = req.get('https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1h&limit=9')
    res.raise_for_status()

    data = res.json()
    print(data)

In [48]:
klines()

[[1776319200000, '75043.47000000', '75115.12000000', '74853.72000000', '75045.01000000', '604.84284000', 1776322799999, '45372964.71765770', 82824, '332.27624000', '24923946.02804110', '0'], [1776322800000, '75045.01000000', '75082.78000000', '74636.00000000', '74707.03000000', '708.06090000', 1776326399999, '53015980.91695830', 91556, '261.83089000', '19598741.18893120', '0'], [1776326400000, '74707.02000000', '74744.35000000', '74500.00000000', '74677.91000000', '669.86210000', 1776329999999, '49975725.56973790', 107568, '303.15331000', '22624229.61624000', '0'], [1776330000000, '74677.91000000', '74901.50000000', '74594.01000000', '74594.02000000', '316.26697000', 1776333599999, '23639051.40946890', 83622, '159.24250000', '11906325.87989400', '0'], [1776333600000, '74594.02000000', '74653.12000000', '74277.34000000', '74313.00000000', '526.53069000', 1776337199999, '39187367.03372670', 116235, '211.33834000', '15728429.30425230', '0'], [1776337200000, '74312.99000000', '74663.27000000', '74285.00000000', '74574.79000000', '1174.61360000', 1776340799999, '87473085.21780410', 89776, '921.51615000', '68632123.73392550', '0'], [1776340800000, '74574.80000000', '74872.00000000', '74574.79000000', '74624.00000000', '529.55969000', 1776344399999, '39541986.23460490', 87567, '259.07189000', '19350491.68329610', '0'], [1776344400000, '74624.01000000', '75030.39000000', '73309.85000000', '73788.03000000', '1828.93731000', 1776347999999, '135699355.79218790', 337317, '741.82725000', '55069624.20513740', '0'], [1776348000000, '73788.03000000', '73970.37000000', '73500.00000000', '73599.52000000', '670.25698000', 1776351599999, '49415184.24332320', 142136, '304.43852000', '22454934.43966810', '0']]

In [49]:
def ticker():
    res = req.get('https://api.binance.com/api/v3/ticker/24hr')
    res.raise_for_status()

    data = res.json()
    print(data[0])

In [50]:
ticker()

{'symbol': 'ETHBTC', 'priceChange': '-0.00030000', 'priceChangePercent': '-0.953', 'weightedAvgPrice': '0.03146527', 'prevClosePrice': '0.03148000', 'lastPrice': '0.03118000', 'lastQty': '2.03740000', 'bidPrice': '0.03118000', 'bidQty': '16.43590000', 'askPrice': '0.03119000', 'askQty': '51.50160000', 'openPrice': '0.03148000', 'highPrice': '0.03177000', 'lowPrice': '0.03112000', 'volume': '14570.77870000', 'quoteVolume': '458.47344014', 'openTime': 1776262881998, 'closeTime': 1776349281998, 'firstId': 528035161, 'lastId': 528082140, 'count': 46980}

In [89]:
import requests as req

class Extract:
    def __init__(self, url):
       self.url = url
    
    def extract_crypto(self):
        response = req.get(self.url)
        response.raise_for_status()

        data = response.json()
        return data

In [123]:
# binance = Extract(url=None)    
prices = Extract("https://api.binance.com/api/v3/ticker/price")
trades = Extract("https://api.binance.com/api/v3/trades?symbol=BTCUSDT&limit=5")
order_book = Extract("https://api.binance.com/api/v3/depth?symbol=BTCUSDT&limit=5")
klines = Extract("https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1h&limit=5")

In [132]:
order_book = order_book.extract_crypto()

In [133]:
bids = order_book.get("bids", [])
asks = order_book.get("asks", [])
print(bids)
print(asks)

[['75000.89000000', '1.09223000'], ['75000.88000000', '0.00079000'], ['75000.78000000', '0.00008000'], ['75000.02000000', '0.00021000'], ['75000.01000000', '0.07904000']]
[['75000.90000000', '3.87274000'], ['75000.91000000', '0.00051000'], ['75000.92000000', '0.00014000'], ['75000.93000000', '0.02113000'], ['75000.94000000', '0.04588000']]

In [134]:
import numpy as np

In [142]:
data = [bid + ask for bid, ask in(zip(bids, asks))]
data

[['75000.89000000', '1.09223000', '75000.90000000', '3.87274000'],
 ['75000.88000000', '0.00079000', '75000.91000000', '0.00051000'],
 ['75000.78000000', '0.00008000', '75000.92000000', '0.00014000'],
 ['75000.02000000', '0.00021000', '75000.93000000', '0.02113000'],
 ['75000.01000000', '0.07904000', '75000.94000000', '0.04588000']]

In [143]:
orders_df = pd.DataFrame(data, columns=["bid_price", "bid_quantity", "ask_price", "ask_quantity"])

In [145]:
from decimal import Decimal

In [147]:
orders_df

        bid_price bid_quantity       ask_price ask_quantity
0  75000.89000000   1.09223000  75000.90000000   3.87274000
1  75000.88000000   0.00079000  75000.91000000   0.00051000
2  75000.78000000   0.00008000  75000.92000000   0.00014000
3  75000.02000000   0.00021000  75000.93000000   0.02113000
4  75000.01000000   0.07904000  75000.94000000   0.04588000

In [124]:
trades = trades.extract_crypto()

In [125]:
from decimal import Decimal

In [126]:
trades_df = pd.DataFrame(trades)
trades_df["price"] = trades_df["price"].apply(Decimal)
trades_df["qty"] = trades_df["qty"].apply(Decimal)
trades_df["quoteQty"] = trades_df["quoteQty"].apply(Decimal)

In [129]:
type(trades_df["time"][0])

numpy.int64

In [148]:
klines = klines.extract_crypto()

klines

[[1776380400000,
  '74867.92000000',
  '75177.76000000',
  '74840.92000000',
  '75154.29000000',
  '224.77396000',
  1776383999999,
  '16868143.63796830',
  82639,
  '121.53187000',
  '9120967.61710140',
  '0'],
 [1776384000000,
  '75154.28000000',
  '75154.77000000',
  '74886.82000000',
  '74944.98000000',
  '796.37355000',
  1776387599999,
  '59698157.76925140',
  77612,
  '337.65889000',
  '25311640.73815550',
  '0'],
 [1776387600000,
  '74944.99000000',
  '75034.49000000',
  '74569.99000000',
  '74750.00000000',
  '407.29847000',
  1776391199999,
  '30462248.49182770',
  76031,
  '199.39051000',
  '14917246.89725770',
  '0'],
 [1776391200000,
  '74750.00000000',
  '74802.98000000',
  '74529.40000000',
  '74700.00000000',
  '235.53372000',
  1776394799999,
  '17583918.89906370',
  62651,
  '85.98615000',
  '6420308.78799220',
  '0'],
 [1776394800000,
  '74700.00000000',
  '74839.31000000',
  '74606.12000000',
  '74746.77000000',
  '654.08727000',
  1776398399999,
  '48860586.50088430',
  67263,
  '319.38822000',
  '23862240.03179040',
  '0']]

In [149]:
columns = ["open_time", "open_price", "high_price", "low_price", "close_price", "volume", "close_time", "quote_asset_volume", "no_of_trades", "base_asset_volume", "quote_asset_volume", "ignore"]

In [150]:
klines_df = pd.DataFrame(klines, columns=columns)

In [151]:
klines_df

,open_time,open_price,high_price,low_price,close_price,volume,close_time,quote_asset_volume,no_of_trades,base_asset_volume,quote_asset_volume,ignore
0,1776380400000,74867.92000000,75177.76000000,74840.92000000,75154.29000000,224.77396000,1776383999999,16868143.63796830,82639,121.53187000,9120967.61710140,0
1,1776384000000,75154.28000000,75154.77000000,74886.82000000,74944.98000000,796.37355000,1776387599999,59698157.76925140,77612,337.65889000,25311640.73815550,0
2,1776387600000,74944.99000000,75034.49000000,74569.99000000,74750.00000000,407.29847000,1776391199999,30462248.49182770,76031,199.39051000,14917246.89725770,0
3,1776391200000,74750.00000000,74802.98000000,74529.40000000,74700.00000000,235.53372000,1776394799999,17583918.89906370,62651,85.98615000,6420308.78799220,0
4,1776394800000,74700.00000000,74839.31000000,74606.12000000,74746.77000000,654.08727000,1776398399999,48860586.50088430,67263,319.38822000,23862240.03179040,0

In [131]:
trades_df

,id,price,qty,quoteQty,time,isBuyerMaker,isBestMatch
0,6224072472,74556.00000000,0.00040000,29.82240000,2026-04-16 18:42:51.615,False,True
1,6224072473,74556.44000000,0.00047000,35.04152680,2026-04-16 18:42:51.615,False,True
2,6224072474,74556.70000000,0.00007000,5.21896900,2026-04-16 18:42:51.615,False,True
3,6224072475,74556.83000000,0.00008000,5.96454640,2026-04-16 18:42:51.615,False,True
4,6224072476,74556.83000000,0.00007000,5.21897810,2026-04-16 18:42:51.615,False,True

In [109]:
print(order_book.extract_crypto())

{'lastUpdateId': 92118031899, 'bids': [['74340.88000000', '2.35387000'], ['74340.87000000', '0.00016000'], ['74340.81000000', '0.00008000'], ['74340.80000000', '0.04499000'], ['74340.00000000', '0.00007000']], 'asks': [['74340.89000000', '2.13904000'], ['74340.90000000', '0.00037000'], ['74341.02000000', '0.00020000'], ['74341.05000000', '0.00009000'], ['74341.36000000', '0.00008000']]}

In [91]:
print(prices.extract_crypto())
print(trades.extract_crypto())
print(order_book.extract_crypto())
print(klines.extract_crypto())

[{'symbol': 'ETHBTC', 'price': '0.03127000'}, {'symbol': 'LTCBTC', 'price': '0.00074500'}, {'symbol': 'BNBBTC', 'price': '0.00838300'}, {'symbol': 'NEOBTC', 'price': '0.00003914'}, {'symbol': 'QTUMETH', 'price': '0.00046550'}, {'symbol': 'EOSETH', 'price': '0.00030670'}, {'symbol': 'SNTETH', 'price': '0.00001700'}, {'symbol': 'BNTETH', 'price': '0.00020260'}, {'symbol': 'BCCBTC', 'price': '0.00000000'}, {'symbol': 'GASBTC', 'price': '0.00002340'}, {'symbol': 'BNBETH', 'price': '0.26810000'}, {'symbol': 'BTCUSDT', 'price': '74218.53000000'}, {'symbol': 'ETHUSDT', 'price': '2321.28000000'}, {'symbol': 'HSRBTC', 'price': '0.00000000'}, {'symbol': 'OAXETH', 'price': '0.00000000'}, {'symbol': 'DNTETH', 'price': '0.00000000'}, {'symbol': 'MCOETH', 'price': '0.00000000'}, {'symbol': 'ICNETH', 'price': '0.00000000'}, {'symbol': 'MCOBTC', 'price': '0.00000000'}, {'symbol': 'WTCBTC', 'price': '0.00000024'}, {'symbol': 'WTCETH', 'price': '0.00000000'}, {'symbol': 'LRCBTC', 'price': '0.00000052'}, {'symbol': 'LRCETH', 'price': '0.00001675'}, {'symbol': 'QTUMBTC', 'price': '0.00001628'}, {'symbol': 'YOYOBTC', 'price': '0.00000000'}, {'symbol': 'OMGBTC', 'price': '0.00003080'}, {'symbol': 'OMGETH', 'price': '0.00079100'}, {'symbol': 'ZRXBTC', 'price': '0.00000154'}, {'symbol': 'ZRXETH', 'price': '0.00009940'}, {'symbol': 'STRATBTC', 'price': '0.00000000'}, {'symbol': 'STRATETH', 'price': '0.00000000'}, {'symbol': 'SNGLSBTC', 'price': '0.00000000'}, {'symbol': 'SNGLSETH', 'price': '0.00000000'}, {'symbol': 'BQXBTC', 'price': '0.00000000'}, {'symbol': 'BQXETH', 'price': '0.00000000'}, {'symbol': 'KNCBTC', 'price': '0.00000185'}, {'symbol': 'KNCETH', 'price': '0.00039410'}, {'symbol': 'FUNBTC', 'price': '0.00000000'}, {'symbol': 'FUNETH', 'price': '0.00000146'}, {'symbol': 'SNMBTC', 'price': '0.00000057'}, {'symbol': 'SNMETH', 'price': '0.00000000'}, {'symbol': 'NEOETH', 'price': '0.00477500'}, {'symbol': 'IOTABTC', 'price': '0.00000076'}, {'symbol': 'IOTAETH', 'price': '0.00003346'}, {'symbol': 'LINKBTC', 'price': '0.00012550'}, {'symbol': 'LINKETH', 'price': '0.00401300'}, {'symbol': 'XVGBTC', 'price': '0.00000000'}, {'symbol': 'XVGETH', 'price': '0.00000247'}, {'symbol': 'SALTBTC', 'price': '0.00000000'}, {'symbol': 'SALTETH', 'price': '0.00000000'}, {'symbol': 'MDABTC', 'price': '0.00000000'}, {'symbol': 'MDAETH', 'price': '0.00000000'}, {'symbol': 'MTLBTC', 'price': '0.00000405'}, {'symbol': 'MTLETH', 'price': '0.00068340'}, {'symbol': 'SUBBTC', 'price': '0.00000000'}, {'symbol': 'SUBETH', 'price': '0.00000000'}, {'symbol': 'EOSBTC', 'price': '0.00000716'}, {'symbol': 'SNTBTC', 'price': '0.00000032'}, {'symbol': 'ETCETH', 'price': '0.00387000'}, {'symbol': 'ETCBTC', 'price': '0.00011420'}, {'symbol': 'MTHBTC', 'price': '0.00000000'}, {'symbol': 'MTHETH', 'price': '0.00000000'}, {'symbol': 'ENGBTC', 'price': '0.00000000'}, {'symbol': 'ENGETH', 'price': '0.00000000'}, {'symbol': 'DNTBTC', 'price': '0.00000186'}, {'symbol': 'ZECBTC', 'price': '0.00451780'}, {'symbol': 'ZECETH', 'price': '0.14440000'}, {'symbol': 'BNTBTC', 'price': '0.00000794'}, {'symbol': 'ASTBTC', 'price': '0.00000124'}, {'symbol': 'ASTETH', 'price': '0.00000000'}, {'symbol': 'DASHBTC', 'price': '0.00049370'}, {'symbol': 'DASHETH', 'price': '0.02084000'}, {'symbol': 'OAXBTC', 'price': '0.00000038'}, {'symbol': 'ICNBTC', 'price': '0.00000000'}, {'symbol': 'BTGBTC', 'price': '0.00091300'}, {'symbol': 'BTGETH', 'price': '0.00000000'}, {'symbol': 'EVXBTC', 'price': '0.00000000'}, {'symbol': 'EVXETH', 'price': '0.00000000'}, {'symbol': 'REQBTC', 'price': '0.00000112'}, {'symbol': 'REQETH', 'price': '0.00000000'}, {'symbol': 'VIBBTC', 'price': '0.00000051'}, {'symbol': 'VIBETH', 'price': '0.00003450'}, {'symbol': 'HSRETH', 'price': '0.00000000'}, {'symbol': 'TRXBTC', 'price': '0.00000440'}, {'symbol': 'TRXETH', 'price': '0.00014060'}, {'symbol': 'POWRBTC', 'price': '0.00000094'}, {'symbol': 'POWRETH', 'price': '0.00002760'}, {'symbol': 'ARKBTC', 'price': '0.00001679'}, {'symbol': 'ARKETH', 'price': '0.00000000'}, {'symbol': 'YOYOETH', 'price': '0.00000000'}, {'symbol': 'XRPBTC', 'price': '0.00001909'}, {'symbol': 'XRPETH', 'price': '0.00061060'}, {'symbol': 'MODBTC', 'price': '0.00000000'}, {'symbol': 'MODETH', 'price': '0.00000000'}, {'symbol': 'ENJBTC', 'price': '0.00000035'}, {'symbol': 'ENJETH', 'price': '0.00006172'}, {'symbol': 'STORJBTC', 'price': '0.00000143'}, {'symbol': 'STORJETH', 'price': '0.00000000'}, {'symbol': 'BNBUSDT', 'price': '622.22000000'}, {'symbol': 'VENBNB', 'price': '0.00000000'}, {'symbol': 'YOYOBNB', 'price': '0.00000000'}, {'symbol': 'POWRBNB', 'price': '0.00000000'}, {'symbol': 'VENBTC', 'price': '0.00000000'}, {'symbol': 'VENETH', 'price': '0.00000000'}, {'symbol': 'KMDBTC', 'price': '0.00000015'}, {'symbol': 'KMDETH', 'price': '0.00000000'}, {'symbol': 'NULSBNB', 'price': '0.00000000'}, {'symbol': 'RCNBTC', 'price': '0.00000000'}, {'symbol': 'RCNETH', 'price': '0.00000000'}, {'symbol': 'RCNBNB', 'price': '0.00000000'}, {'symbol': 'NULSBTC', 'price': '0.00000030'}, {'symbol': 'NULSETH', 'price': '0.00000000'}, {'symbol': 'RDNBTC', 'price': '0.00000000'}, {'symbol': 'RDNETH', 'price': '0.00000000'}, {'symbol': 'RDNBNB', 'price': '0.00000000'}, {'symbol': 'XMRBTC', 'price': '0.00228700'}, {'symbol': 'XMRETH', 'price': '0.04032000'}, {'symbol': 'DLTBNB', 'price': '0.00000000'}, {'symbol': 'WTCBNB', 'price': '0.00000000'}, {'symbol': 'DLTBTC', 'price': '0.00000000'}, {'symbol': 'DLTETH', 'price': '0.00000000'}, {'symbol': 'AMBBTC', 'price': '0.00000010'}, {'symbol': 'AMBETH', 'price': '0.00000000'}, {'symbol': 'AMBBNB', 'price': '0.00000000'}, {'symbol': 'BCCETH', 'price': '0.00000000'}, {'symbol': 'BCCUSDT', 'price': '0.00000000'}, {'symbol': 'BCCBNB', 'price': '0.00000000'}, {'symbol': 'BATBTC', 'price': '0.00000135'}, {'symbol': 'BATETH', 'price': '0.00010630'}, {'symbol': 'BATBNB', 'price': '0.00000000'}, {'symbol': 'BCPTBTC', 'price': '0.00000000'}, {'symbol': 'BCPTETH', 'price': '0.00000000'}, {'symbol': 'BCPTBNB', 'price': '0.00000000'}, {'symbol': 'ARNBTC', 'price': '0.00000000'}, {'symbol': 'ARNETH', 'price': '0.00000000'}, {'symbol': 'GVTBTC', 'price': '0.00000000'}, {'symbol': 'GVTETH', 'price': '0.00000000'}, {'symbol': 'CDTBTC', 'price': '0.00000000'}, {'symbol': 'CDTETH', 'price': '0.00000000'}, {'symbol': 'GXSBTC', 'price': '0.00000000'}, {'symbol': 'GXSETH', 'price': '0.00000000'}, {'symbol': 'NEOUSDT', 'price': '2.90400000'}, {'symbol': 'NEOBNB', 'price': '0.03836000'}, {'symbol': 'POEBTC', 'price': '0.00000000'}, {'symbol': 'POEETH', 'price': '0.00000000'}, {'symbol': 'QSPBTC', 'price': '0.00000000'}, {'symbol': 'QSPETH', 'price': '0.00000000'}, {'symbol': 'QSPBNB', 'price': '0.00000000'}, {'symbol': 'BTSBTC', 'price': '0.00000043'}, {'symbol': 'BTSETH', 'price': '0.00000000'}, {'symbol': 'BTSBNB', 'price': '0.00000000'}, {'symbol': 'XZCBTC', 'price': '0.00000000'}, {'symbol': 'XZCETH', 'price': '0.00000000'}, {'symbol': 'XZCBNB', 'price': '0.00000000'}, {'symbol': 'LSKBTC', 'price': '0.00000186'}, {'symbol': 'LSKETH', 'price': '0.00033730'}, {'symbol': 'LSKBNB', 'price': '0.00000000'}, {'symbol': 'TNTBTC', 'price': '0.00000000'}, {'symbol': 'TNTETH', 'price': '0.00000000'}, {'symbol': 'FUELBTC', 'price': '0.00000000'}, {'symbol': 'FUELETH', 'price': '0.00000000'}, {'symbol': 'MANABTC', 'price': '0.00000147'}, {'symbol': 'MANAETH', 'price': '0.00004950'}, {'symbol': 'BCDBTC', 'price': '0.00000000'}, {'symbol': 'BCDETH', 'price': '0.00000000'}, {'symbol': 'DGDBTC', 'price': '0.00000000'}, {'symbol': 'DGDETH', 'price': '0.00000000'}, {'symbol': 'IOTABNB', 'price': '0.00071700'}, {'symbol': 'ADXBTC', 'price': '0.00000105'}, {'symbol': 'ADXETH', 'price': '0.00003007'}, {'symbol': 'ADXBNB', 'price': '0.00000000'}, {'symbol': 'ADABTC', 'price': '0.00000336'}, {'symbol': 'ADAETH', 'price': '0.00010750'}, {'symbol': 'PPTBTC', 'price': '0.00000000'}, {'symbol': 'PPTETH', 'price': '0.00000000'}, {'symbol': 'CMTBTC', 'price': '0.00000000'}, {'symbol': 'CMTETH', 'price': '0.00000000'}, {'symbol': 'CMTBNB', 'price': '0.00000000'}, {'symbol': 'XLMBTC', 'price': '0.00000218'}, {'symbol': 'XLMETH', 'price': '0.00006938'}, {'symbol': 'XLMBNB', 'price': '0.00030360'}, {'symbol': 'CNDBTC', 'price': '0.00000000'}, {'symbol': 'CNDETH', 'price': '0.00000000'}, {'symbol': 'CNDBNB', 'price': '0.00000000'}, {'symbol': 'LENDBTC', 'price': '0.00000000'}, {'symbol': 'LENDETH', 'price': '0.00000000'}, {'symbol': 'WABIBTC', 'price': '0.00000030'}, {'symbol': 'WABIETH', 'price': '0.00000000'}, {'symbol': 'WABIBNB', 'price': '0.00000000'}, {'symbol': 'LTCETH', 'price': '0.02380000'}, {'symbol': 'LTCUSDT', 'price': '55.28000000'}, {'symbol': 'LTCBNB', 'price': '0.08900000'}, {'symbol': 'TNBBTC', 'price': '0.00000000'}, {'symbol': 'TNBETH', 'price': '0.00000000'}, {'symbol': 'WAVESBTC', 'price': '0.00001626'}, {'symbol': 'WAVESETH', 'price': '0.00029800'}, {'symbol': 'WAVESBNB', 'price': '0.00513000'}, {'symbol': 'GTOBTC', 'price': '0.00000077'}, {'symbol': 'GTOETH', 'price': '0.00000000'}, {'symbol': 'GTOBNB', 'price': '0.00000000'}, {'symbol': 'ICXBTC', 'price': '0.00000056'}, {'symbol': 'ICXETH', 'price': '0.00011790'}, {'symbol': 'ICXBNB', 'price': '0.00000000'}, {'symbol': 'OSTBTC', 'price': '0.00000000'}, {'symbol': 'OSTETH', 'price': '0.00000000'}, {'symbol': 'OSTBNB', 'price': '0.00000000'}, {'symbol': 'ELFBTC', 'price': '0.00000274'}, {'symbol': 'ELFETH', 'price': '0.00014330'}, {'symbol': 'AIONBTC', 'price': '0.00000139'}, {'symbol': 'AIONETH', 'price': '0.00000000'}, {'symbol': 'AIONBNB', 'price': '0.00000000'}, {'symbol': 'NEBLBTC', 'price': '0.00001200'}, {'symbol': 'NEBLBNB', 'price': '0.00000000'}, {'symbol': 'BRDBTC', 'price': '0.00000000'}, {'symbol': 'BRDETH', 'price': '0.00000000'}, {'symbol': 'BRDBNB', 'price': '0.00000000'}, {'symbol': 'MCOBNB', 'price': '0.00000000'}, {'symbol': 'EDOBTC', 'price': '0.00000000'}, {'symbol': 'EDOETH', 'price': '0.00000000'}, {'symbol': 'WINGSBTC', 'price': '0.00000000'}, {'symbol': 'WINGSETH', 'price': '0.00000000'}, {'symbol': 'NAVBTC', 'price': '0.00000000'}, {'symbol': 'NAVETH', 'price': '0.00000000'}, {'symbol': 'NAVBNB', 'price': '0.00000000'}, {'symbol': 'LUNBTC', 'price': '0.00000000'}, {'symbol': 'LUNETH', 'price': '0.00000000'}, {'symbol': 'TRIGBTC', 'price': '0.00000000'}, {'symbol': 'TRIGETH', 'price': '0.00000000'}, {'symbol': 'TRIGBNB', 'price': '0.00000000'}, {'symbol': 'APPCBTC', 'price': '0.00000000'}, {'symbol': 'APPCETH', 'price': '0.00000000'}, {'symbol': 'APPCBNB', 'price': '0.00000000'}, {'symbol': 'VIBEBTC', 'price': '0.00000000'}, {'symbol': 'VIBEETH', 'price': '0.00000000'}, {'symbol': 'RLCBTC', 'price': '0.00000553'}, {'symbol': 'RLCETH', 'price': '0.00018340'}, {'symbol': 'RLCBNB', 'price': '0.00000000'}, {'symbol': 'INSBTC', 'price': '0.00000000'}, {'symbol': 'INSETH', 'price': '0.00000000'}, {'symbol': 'PIVXBTC', 'price': '0.00000147'}, {'symbol': 'PIVXBNB', 'price': '0.00000000'}, {'symbol': 'IOSTBTC', 'price': '0.00000010'}, {'symbol': 'IOSTETH', 'price': '0.00000372'}, {'symbol': 'CHATBTC', 'price': '0.00000000'}, {'symbol': 'CHATETH', 'price': '0.00000000'}, {'symbol': 'STEEMBTC', 'price': '0.00000079'}, {'symbol': 'STEEMETH', 'price': '0.00002554'}, {'symbol': 'STEEMBNB', 'price': '0.00000000'}, {'symbol': 'NANOBTC', 'price': '0.00000000'}, {'symbol': 'NANOETH', 'price': '0.00000000'}, {'symbol': 'NANOBNB', 'price': '0.00000000'}, {'symbol': 'VIABTC', 'price': '0.00000000'}, {'symbol': 'VIAETH', 'price': '0.00000000'}, {'symbol': 'VIABNB', 'price': '0.00000000'}, {'symbol': 'BLZBTC', 'price': '0.00000060'}, {'symbol': 'BLZETH', 'price': '0.00004159'}, {'symbol': 'BLZBNB', 'price': '0.00000000'}, {'symbol': 'AEBTC', 'price': '0.00000000'}, {'symbol': 'AEETH', 'price': '0.00000000'}, {'symbol': 'AEBNB', 'price': '0.00000000'}, {'symbol': 'RPXBTC', 'price': '0.00000000'}, {'symbol': 'RPXETH', 'price': '0.00000000'}, {'symbol': 'RPXBNB', 'price': '0.00000000'}, {'symbol': 'NCASHBTC', 'price': '0.00000000'}, {'symbol': 'NCASHETH', 'price': '0.00000000'}, {'symbol': 'NCASHBNB', 'price': '0.00000000'}, {'symbol': 'POABTC', 'price': '0.00000000'}, {'symbol': 'POAETH', 'price': '0.00000000'}, {'symbol': 'POABNB', 'price': '0.00000000'}, {'symbol': 'ZILBTC', 'price': '0.00000010'}, {'symbol': 'ZILETH', 'price': '0.00000168'}, {'symbol': 'ZILBNB', 'price': '0.00008858'}, {'symbol': 'ONTBTC', 'price': '0.00000100'}, {'symbol': 'ONTETH', 'price': '0.00012530'}, {'symbol': 'ONTBNB', 'price': '0.00000000'}, {'symbol': 'STORMBTC', 'price': '0.00000000'}, {'symbol': 'STORMETH', 'price': '0.00000000'}, {'symbol': 'STORMBNB', 'price': '0.00000000'}, {'symbol': 'QTUMBNB', 'price': '0.00000000'}, {'symbol': 'QTUMUSDT', 'price': '0.91400000'}, {'symbol': 'XEMBTC', 'price': '0.00000192'}, {'symbol': 'XEMETH', 'price': '0.00000000'}, {'symbol': 'XEMBNB', 'price': '0.00000000'}, {'symbol': 'WANBTC', 'price': '0.00000076'}, {'symbol': 'WANETH', 'price': '0.00009270'}, {'symbol': 'WANBNB', 'price': '0.00000000'}, {'symbol': 'WPRBTC', 'price': '0.00000000'}, {'symbol': 'WPRETH', 'price': '0.00000000'}, {'symbol': 'QLCBTC', 'price': '0.00000021'}, {'symbol': 'QLCETH', 'price': '0.00000000'}, {'symbol': 'SYSBTC', 'price': '0.00000019'}, {'symbol': 'SYSETH', 'price': '0.00000000'}, {'symbol': 'SYSBNB', 'price': '0.00000000'}, {'symbol': 'QLCBNB', 'price': '0.00000000'}, {'symbol': 'GRSBTC', 'price': '0.00000000'}, {'symbol': 'GRSETH', 'price': '0.00000000'}, {'symbol': 'ADAUSDT', 'price': '0.24960000'}, {'symbol': 'ADABNB', 'price': '0.00040100'}, {'symbol': 'CLOAKBTC', 'price': '0.00000000'}, {'symbol': 'CLOAKETH', 'price': '0.00000000'}, {'symbol': 'GNTBTC', 'price': '0.00000000'}, {'symbol': 'GNTETH', 'price': '0.00000000'}, {'symbol': 'GNTBNB', 'price': '0.00000000'}, {'symbol': 'LOOMBTC', 'price': '0.00000075'}, {'symbol': 'LOOMETH', 'price': '0.00003231'}, {'symbol': 'LOOMBNB', 'price': '0.00000000'}, {'symbol': 'XRPUSDT', 'price': '1.41750000'}, {'symbol': 'BCNBTC', 'price': '0.00000000'}, {'symbol': 'BCNETH', 'price': '0.00000000'}, {'symbol': 'BCNBNB', 'price': '0.00000000'}, {'symbol': 'REPBTC', 'price': '0.00034130'}, {'symbol': 'REPBNB', 'price': '0.00000000'}, {'symbol': 'BTCTUSD', 'price': '74314.55000000'}, {'symbol': 'TUSDBTC', 'price': '0.00000000'}, {'symbol': 'ETHTUSD', 'price': '2324.65000000'}, {'symbol': 'TUSDETH', 'price': '0.00000000'}, {'symbol': 'TUSDBNB', 'price': '0.00000000'}, {'symbol': 'ZENBTC', 'price': '0.00007817'}, {'symbol': 'ZENETH', 'price': '0.00399100'}, {'symbol': 'ZENBNB', 'price': '0.03290000'}, {'symbol': 'SKYCOINBTC', 'price': '0.00000000'}, {'symbol': 'SKYCOINETH', 'price': '0.00000000'}, {'symbol': 'SKYCOINBNB', 'price': '0.00000000'}, {'symbol': 'EOSUSDT', 'price': '0.77990000'}, {'symbol': 'EOSBNB', 'price': '0.00258300'}, {'symbol': 'CVCBTC', 'price': '0.00000566'}, {'symbol': 'CVCETH', 'price': '0.00000000'}, {'symbol': 'CVCBNB', 'price': '0.00000000'}, {'symbol': 'THETABTC', 'price': '0.00000261'}, {'symbol': 'THETAETH', 'price': '0.00050170'}, {'symbol': 'THETABNB', 'price': '0.00273600'}, {'symbol': 'XRPBNB', 'price': '0.00227710'}, {'symbol': 'TUSDUSDT', 'price': '0.99910000'}, {'symbol': 'IOTAUSDT', 'price': '0.05640000'}, {'symbol': 'XLMUSDT', 'price': '0.16120000'}, {'symbol': 'IOTXBTC', 'price': '0.00000009'}, {'symbol': 'IOTXETH', 'price': '0.00000300'}, {'symbol': 'QKCBTC', 'price': '0.00000010'}, {'symbol': 'QKCETH', 'price': '0.00000430'}, {'symbol': 'AGIBTC', 'price': '0.00000000'}, {'symbol': 'AGIETH', 'price': '0.00000000'}, {'symbol': 'AGIBNB', 'price': '0.00000000'}, {'symbol': 'NXSBTC', 'price': '0.00000000'}, {'symbol': 'NXSETH', 'price': '0.00000000'}, {'symbol': 'NXSBNB', 'price': '0.00000000'}, {'symbol': 'ENJBNB', 'price': '0.00136800'}, {'symbol': 'DATABTC', 'price': '0.00000008'}, {'symbol': 'DATAETH', 'price': '0.00002034'}, {'symbol': 'ONTUSDT', 'price': '0.07370000'}, {'symbol': 'TRXBNB', 'price': '0.00052470'}, {'symbol': 'TRXUSDT', 'price': '0.32640000'}, {'symbol': 'ETCUSDT', 'price': '8.48000000'}, {'symbol': 'ETCBNB', 'price': '0.01416000'}, {'symbol': 'ICXUSDT', 'price': '0.03870000'}, {'symbol': 'SCBTC', 'price': '0.00000000'}, {'symbol': 'SCETH', 'price': '0.00000049'}, {'symbol': 'NPXSBTC', 'price': '0.00000000'}, {'symbol': 'NPXSETH', 'price': '0.00000000'}, {'symbol': 'VENUSDT', 'price': '0.00000000'}, {'symbol': 'KEYBTC', 'price': '0.00000000'}, {'symbol': 'KEYETH', 'price': '0.00000227'}, {'symbol': 'NASBTC', 'price': '0.00000000'}, {'symbol': 'NASETH', 'price': '0.00000000'}, {'symbol': 'NASBNB', 'price': '0.00000000'}, {'symbol': 'MFTBTC', 'price': '0.00000000'}, {'symbol': 'MFTETH', 'price': '0.00000433'}, {'symbol': 'MFTBNB', 'price': '0.00000000'}, {'symbol': 'DENTBTC', 'price': '0.00000000'}, {'symbol': 'DENTETH', 'price': '0.00000007'}, {'symbol': 'ARDRBTC', 'price': '0.00000065'}, {'symbol': 'ARDRETH', 'price': '0.00000000'}, {'symbol': 'ARDRBNB', 'price': '0.00000000'}, {'symbol': 'NULSUSDT', 'price': '0.02580000'}, {'symbol': 'HOTBTC', 'price': '0.00000000'}, {'symbol': 'HOTETH', 'price': '0.00000017'}, {'symbol': 'VETBTC', 'price': '0.00000009'}, {'symbol': 'VETETH', 'price': '0.00000344'}, {'symbol': 'VETUSDT', 'price': '0.00713300'}, {'symbol': 'VETBNB', 'price': '0.00001339'}, {'symbol': 'DOCKBTC', 'price': '0.00000005'}, {'symbol': 'DOCKETH', 'price': '0.00000000'}, {'symbol': 'POLYBTC', 'price': '0.00001384'}, {'symbol': 'POLYBNB', 'price': '0.00000000'}, {'symbol': 'PHXBTC', 'price': '0.00000000'}, {'symbol': 'PHXETH', 'price': '0.00000000'}, {'symbol': 'PHXBNB', 'price': '0.00000000'}, {'symbol': 'HCBTC', 'price': '0.00000000'}, {'symbol': 'HCETH', 'price': '0.00000000'}, {'symbol': 'GOBTC', 'price': '0.00000000'}, {'symbol': 'GOBNB', 'price': '0.00000000'}, {'symbol': 'PAXBTC', 'price': '0.00000000'}, {'symbol': 'PAXBNB', 'price': '0.00000000'}, {'symbol': 'PAXUSDT', 'price': '0.00000000'}, {'symbol': 'PAXETH', 'price': '0.00000000'}, {'symbol': 'RVNBTC', 'price': '0.00000010'}, {'symbol': 'DCRBTC', 'price': '0.00021850'}, {'symbol': 'DCRBNB', 'price': '0.00000000'}, {'symbol': 'USDCBNB', 'price': '0.00000000'}, {'symbol': 'MITHBTC', 'price': '0.00000080'}, {'symbol': 'MITHBNB', 'price': '0.00004410'}, {'symbol': 'BCHABCBTC', 'price': '0.00000000'}, {'symbol': 'BCHSVBTC', 'price': '0.00000000'}, {'symbol': 'BCHABCUSDT', 'price': '0.00000000'}, {'symbol': 'BCHSVUSDT', 'price': '0.00000000'}, {'symbol': 'BNBPAX', 'price': '0.00000000'}, {'symbol': 'BTCPAX', 'price': '0.00000000'}, {'symbol': 'ETHPAX', 'price': '0.00000000'}, {'symbol': 'XRPPAX', 'price': '0.00000000'}, {'symbol': 'EOSPAX', 'price': '0.00000000'}, {'symbol': 'XLMPAX', 'price': '0.00000000'}, {'symbol': 'RENBTC', 'price': '0.00000043'}, {'symbol': 'RENBNB', 'price': '0.00000000'}, {'symbol': 'BNBTUSD', 'price': '605.48000000'}, {'symbol': 'XRPTUSD', 'price': '1.31780000'}, {'symbol': 'EOSTUSD', 'price': '0.00000000'}, {'symbol': 'XLMTUSD', 'price': '0.00000000'}, {'symbol': 'BNBUSDC', 'price': '622.28000000'}, {'symbol': 'BTCUSDC', 'price': '74243.78000000'}, {'symbol': 'ETHUSDC', 'price': '2322.11000000'}, {'symbol': 'XRPUSDC', 'price': '1.41810000'}, {'symbol': 'EOSUSDC', 'price': '0.77780000'}, {'symbol': 'XLMUSDC', 'price': '0.16130000'}, {'symbol': 'USDCUSDT', 'price': '0.99968000'}, {'symbol': 'ADATUSD', 'price': '0.38470000'}, {'symbol': 'TRXTUSD', 'price': '0.05986000'}, {'symbol': 'NEOTUSD', 'price': '0.00000000'}, {'symbol': 'TRXXRP', 'price': '0.23080000'}, {'symbol': 'XZCXRP', 'price': '0.00000000'}, {'symbol': 'PAXTUSD', 'price': '0.00000000'}, {'symbol': 'USDCTUSD', 'price': '0.00000000'}, {'symbol': 'USDCPAX', 'price': '0.00000000'}, {'symbol': 'LINKUSDT', 'price': '9.32000000'}, {'symbol': 'LINKTUSD', 'price': '14.42300000'}, {'symbol': 'LINKPAX', 'price': '0.00000000'}, {'symbol': 'LINKUSDC', 'price': '9.33000000'}, {'symbol': 'WAVESUSDT', 'price': '1.07600000'}, {'symbol': 'WAVESTUSD', 'price': '0.00000000'}, {'symbol': 'WAVESPAX', 'price': '0.00000000'}, {'symbol': 'WAVESUSDC', 'price': '0.00000000'}, {'symbo

In [83]:
import pandas as pd

In [102]:
from decimal import Decimal

In [106]:
prices = prices.extract_crypto()

_df = pd.DataFrame(prices)

_df["price"] = _df["price"].apply(Decimal)

print(type(_df["price"].get("price")))

# print(type(prices))
# def transform():
#     for price in prices:
#         p
#     _df = pd.DataFrame(prices)
#     print(_df)

<class 'NoneType'>

In [107]:
print(type(_df["price"][0]))

<class 'decimal.Decimal'>

In [108]:
_df

         symbol           price
0        ETHBTC      0.03123000
1        LTCBTC      0.00074600
2        BNBBTC      0.00840500
3        NEOBTC      0.00003914
4       QTUMETH      0.00046550
...         ...             ...
3557       WLDU      0.32080000
3558  TRUMPUSD1      2.97800000
3559    BTCUSDS  74512.63000000
3560    ETHUSDS   2321.40000000
3561   USDSUSDT      0.99950000

[3562 rows x 2 columns]

In [87]:
type(prices[0].get("price"))
print(prices[0].get("price"))

0.03130000

In [70]:
transform()

         symbol           price
0        ETHBTC      0.03123000
1        LTCBTC      0.00074300
2        BNBBTC      0.00837800
3        NEOBTC      0.00003914
4       QTUMETH      0.00046550
...         ...             ...
3557       WLDU      0.31060000
3558  TRUMPUSD1      2.92900000
3559    BTCUSDS  73508.57000000
3560    ETHUSDS   2308.55000000
3561   USDSUSDT      0.99950000

[3562 rows x 2 columns]

In [154]:
import requests as req

class Extract:
    def __init__(self, url):
        self.url = url
    
    def extract_crypto(url):
        response = req.get(url)
        response.raise_for_status()

        data = response.json()
        return data
    
prices = Extract("https://api.binance.com/api/v3/ticker/price")
trades = Extract("https://api.binance.com/api/v3/trades?symbol=BTCUSDT&limit=5")
order_book = Extract("https://api.binance.com/api/v3/depth?symbol=BTCUSDT&limit=5")
klines = Extract("https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1h&limit=5")
    

print(prices.extract_crypto())
print(trades.extract_crypto())
print(order_book.extract_crypto())
print(klines.extract_crypto())

MissingSchema: Invalid URL '<__main__.Extract object at 0x00000266FBC742F0>': No scheme supplied. Perhaps you meant https://<__main__.Extract object at 0x00000266FBC742F0>?